### ISSUE TITLE
Cases list (app & web) [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#103]
- [x] add short names for diseases: EVD, Lassa, Cholera, CSM, HPAI, Measles
- [x] use short names in grid
- [x] use short names in app list
- [x] add report date in line of reporting user
- [x] order by date of report (newest first)
- [x] grid: split person name into first name and last name columns
- [x] search: case id, first name, last name

TODO: same for contacts & events?

**Comment by MateStrysewskeSym** [comment]
Splitting the person name into two columns doesn't seem reasonable to me, is there any specific reason why we need to do this? Searching both by first and last name works fine with a single column.

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym For epidemiological demographic reasons it makes sense to split the person name into two columns even though you can search by first name and last name. Lets do it please. Thanks

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Alright, implemented it as requested!

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym  Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] show date of report in cases list of mobile app
