### ISSUE TITLE
Move a case to another health facility (POS 7) [2+X]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#104]
Once a case has been turfed to a new officer , the tasks & contacts should also move to him
Now something to keep in mind , when it comes to generating statistics, is to define to what lga a case is assigned to in counting. It is of course clear that it will not be counted twice , my suggestion would be to count it with assignment to the actual most recent lga and not to a previous one. 

Separately form that one may make stats stratified by origin of infection. In that case the first lga would be the one to assign it to.
@MartinWahnschaffeSymeda  @gstephan30 @stoikkanen

**Comment by gstephan30** [comment]
I agree with the most recent one. 
Regarding statistics: case creation should have lga info,and in case its moved (which should also be represented in the data) the new lga should be given. 
/discuss

**Comment by stoikkanen** [comment]
Yes

**Comment by MartinWahnschaffeSymeda** [comment]
Based on our discussion yesterday:
Informants, officers and supervisors should be able to move a case to another health facility. This should be handled in a dedicated user interface. If the district or region of the case changes the system should automatically assign new responsible supervisors and officers and move associated tasks accordingly (e.g. case investigation to the surveillance supervisor of the new LGA). In addition the list of previous hospitalizations should automatically be updated and the health facility the case was originally reported has to be provided.

Questions:
1. Do we need a full movement history (aside from the previous hospitalizations and the database history) or is it sufficient to provide the current and the original health facility to the user?
2. Which users should be informed when a case is moved and how? The new responsible officers will probably receive tasks anyway.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] when changing the LGA of a case in the app and synchronizing, the responsible officers should automatically be updated (should probably be done in CaseFacade.saveCase):
  * when the new LGA has exactly one officer -> use this one
  * when there is multiple or none -> set none (task will be created)

Discuss:
- [ ] when the health facility is changed the system automatically creates a new previous hospitalization using the data from the case and current hospitalization
- [ ] maybe move case data and hospitalization together

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] pre-select officer when there is only one in the lga
- [ ] crash when none health facility was set and the case moved to a facility in another lga. Then went to prev hosp and selected it.
