### ISSUE TITLE
Import laboratories (public labs of nigeria) [0.5]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#105]
@MartinWahnschaffeSymeda @gstephan30 @StefanSzczesny 
[NCDC proposed Laboratory reporting format in the Network March 21 2016 XX.pdf](https://github.com/hzi-braunschweig/SORMAS-Open/files/735542/NCDC.proposed.Laboratory.reporting.format.in.the.Network.March.21.2016.XX.pdf)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] create csv with the ~10 labs from above pdf (see sormas-backend/resources/facilities to get an idea of what this could look like)
- [ ] write import methode (see ~ MockupDataGenerator.importFacilities)
- [ ] call in StartupShutdownService
- [ ] add query method to FacilityService
