### ISSUE TITLE
Samples list [2]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#107]
- [x] sample grid: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/adc9a738c
- [x] create SampleIndexDto to mix sample, case data and tests
- [x] search and filters
- [x] also within a case

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Have a look into the moqups for the changes on shipment status and "no test possible"

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add list of SampleTests in Sample entity and use it in EJB
