### ISSUE TITLE
Sample create / edit view [1]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#108]
- [x] create sample form:https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a2a53e848
- [x] sample controller
- [x] create sample 
- [x] edit sample 
- [x] update required fields for sample form
- [x] styling

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Layout of moqup is updated

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] split SampleDateTime in UI like in Task (due date)
- [ ] merge SampleCreateForm and SampleEditForm

**Comment by MateStrysewskeSym** [comment]
SampleCreateForm and SampleEditForm can't be easily merged because the overridden methods are called before the constructor of the form itself is called.
