### ISSUE TITLE
Update web login screen

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#109]
@dta16 
- [x] create a mockup of how the web login page should look like

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Can you please have a look at where the picture is taken from and make sure it's public domain or anything we can use?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda I got it from a free domain for images. If it were not public domain it would have water mark on it. So I am guessing we can use it. I have also checked online and found the image originated from 
![fifa](https://cloud.githubusercontent.com/assets/19344651/22550431/4ad34bc4-e950-11e6-9ea3-71f7e5adbb1a.PNG)

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 
Have you created a mockup for the new login page with the sormas logo and discussed it yet?

**Comment by MartinWahnschaffeSymeda** [comment]
mockups have been posted in #131

**Comment by MartinWahnschaffeSymeda** [comment]
Done as discussed in #131

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda I think for the write up on the left side of the web login screen, we can have the following text boldly captioned:
SORMAS stands for “Surveillance, Outbreak Response Management and Analysis System“
DISEASE PREVENTION
DISEASE DETECTION &
OUTBREAK RESPONSE

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Can you edit this with the firefox in-browser editor and create a screenshot so the others can see and confirm it?

**Comment by hzi-braunschweig** [comment]
Ok See below

![image](https://cloud.githubusercontent.com/assets/19344651/24403917/5133ecdc-13bf-11e7-8d77-3b6426128f16.png)
