### ISSUE TITLE
Add LabUser user role [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#111]
- [x] extend UserRole enum
- [x] i18n properties
- [x] make sure UserEditForm shows the new role
- [x] add Laboratory property to user entity and dto (+ add comment to health facility that makes clear this property is used for the informant)
- [x] Add laboratory field to UserEditForm that is visible and required  when LabUser
- [x] add caption for lab and health facility field
- [x] add Admin role that is allowed to create supervisors and lab users
- [x] make sure Admin exists on our test systems

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda A new role for the National Reference Laboratory is needed to separate the regional and district level labs from the national labs. @MateStrysewskeSym
