### ISSUE TITLE
Add geo coordinates to health facilities [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#115]
- [x] organize geo coordinates - use at least those of the wards
- [x] extend health facility import with geo coordinates

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda I have requested from the Nigeria team. Hoping they send something to me soon. Meanwhile this list might also be helpful in terms of measure @stoikkanen @gstephan30 
[List and number of all HFs in Nigeria.xlsx](https://github.com/hzi-braunschweig/SORMAS-Open/files/748208/List.and.number.of.all.HFs.in.Nigeria.xlsx)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym @Krisistis @gstephan30 Hallo Guys. I finally got the geocoordinates for the health facilities in Nigeria. At this link https://www.dropbox.com/s/6sdh98s9szuhyax/Health_Merged_Complete%20A.csv?dl=0 please also use information on health facilities and integrate into SORMAS (active or not, public or private, access etc). We can discuss this later. Can you integrate asap? Thanks

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Getting this data into SORMAS will be a pretty tough task from what I can see, because, again, there are a lot of names spelt differently and it's a lot of data. We probably will do this as early as possible next week.

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym You can trim the other data attributes and only use the health facility names, States, LGAs, and Geo Coordinates. 

Regards

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Yes, of course, but due to the naming issues, it's still a lot of data to go through - maybe we can do this semi-automatically, but we'll have to look into that.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 
We wont be able to get this into SORMAS quickly.
There are serveral problems. For some there is a clear (but time consuming) solution.

- The lgas have a completely different naming schema. E.g. "owerri_north" instead of "Owerri North". This is not a big deal 
  -> lowercase the whole thing and replace spaces with underscores
- ward names are inconsistent. E.g. "Aliade Mbalav", "Aliade/mbalaav", "Aliade/mbalav"
  -> no idea what to do about this. Maybe we could do a similarity search, but this will take time
- 10% of facilities have numbers as wards (e.g. line 191, 526, 753, ...)
  -> ???
- Facility names often don't match those in SORMAS
  -> drop all facilities and freshly import

**Comment by MartinWahnschaffeSymeda** [comment]
Our solution: Don't use the wards for the health facilites. Instead show all the health facilities of an LGA.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] set all usages of health facilities to null (case, user, person)
- [ ] drop existing health facilities
- [ ] remove not needed columns from facilities file and put it as csv into the backend
- [ ] replace underscores ("_") in lga names with whitespace (" ")
- [ ] import health facilities. Match LGA case insensitive. If ward name matches as well, set the ward, otherwise leave it empty
- [ ] ui: health facility select fields are filled based on LGA instead of ward. Nevertheless, ward fields can be entered by the user and are required for a case
- [ ] same for app

@hzi-braunschweig 
Please not that you will have to set the health facility for all informants after the next release.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] when a case is persisted check whether the health facility has geo coordinates. If it doesn't, use the case's report coordinates

**Comment by MateStrysewskeSym** [comment]
Code has been commented out until #325 is fixed.

**Comment by MartinWahnschaffeSymeda** [comment]
Done in ac2bafdd
