### ISSUE TITLE
Case creation using first and last name [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#118]
Do it the same way contacts are created

- [x] moqups
- [x] web ui
- [x] mobile app

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda I am having serious synchronization issues with the contact app. 
[] assigning a contact to a contact officer of a source case who is not created by the contact officer
[] viewing tasks associated with the contact officer with respect to the assigned contact person
[] creation of new contact by contact officer and assigning to source case

**Comment by MartinWahnschaffeSymeda** [comment]
see #125

**Comment by MartinWahnschaffeSymeda** [comment]
creation in web ui is done
