### ISSUE TITLE
Epidemiological data in webapp [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#119]
- [x] refine data dictionary: epidemiological data is part of new EpiData entity
- [x] update epi moqup (https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a3ac2d54d)
- [x] create EpiData, EpiBurial, EpiGathering, EpiTravel entity
- [x] EpiDataDto (including lists of burials, gatherings, travels), Facade, Service
- [x] ui view

**Comment by MartinWahnschaffeSymeda** [comment]
Feedback to the mockup:

* gatherings should also be list (like burials)
* travels should also be list (like burials)
* animal fields should be yes/no/unk like in symptoms

**Comment by MateStrysewskeSym** [comment]
@stoikkanen the field "poultryeat" doesn't have any diseases associated with it. Should it be used for all diseases or only some of them? If so, could you update the data dictionary accordingly (see https://docs.google.com/spreadsheets/d/1BA_RjM-ZhxFrzpAJdv0UVGhicHXNP6JnPBA-xzdrQKs/edit#gid=370159711)? Thanks!

**Comment by stoikkanen** [comment]
Hallo,
es ist relevant nunn für die HPAI

Grüße,
Salla

**Comment by MateStrysewskeSym** [comment]
@stoikkanen Okay, thank you. :)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make sure that existing cases have hospitalizations and epi data (SQL)
