### ISSUE TITLE
Event data sync [0.5]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#123]
moved from #69 
- [x] sync event persons together with events (app)
- [x] backend: sync event persons based on events
- [x] create/update persons if needed (app)
- [x] make sure empty location is created together with event
- [x] add UserFilter to EventParticipantService that retrieves all participants of events the user can access (needs a different call than e.g. in Sample and SampleTest)
- [x] display event date in app list (not report date and time)

**Comment by hzi-braunschweig** [comment]
@StefanSzczesny @MartinWahnschaffeSymeda Thanks for sending the updates. Please I cant do anything on the event instance on themobile app. Sormas just keeps crashing. We cant test this section if this continues. Any ideas why? I cant add a new event on the mobile app. App crashes. Please help SOS

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda No data is saved when created for the event. Please help!

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Should be fixed, sorry for the issues. We'll make a new release right now and inform you as soon as it's done and you can download the new app version.
