### ISSUE TITLE
Case Creation: New case (Surveillance supervisor)

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#124]
@MartinWahnschaffeSymeda @StefanSzczesny For the web app UI, the supervisor cannot create a new case from his instance, as shown in the images, even if he clicks the plus button he creates the name of the case and comes back to add the new case, the new case name does not show if typed on search function, also if i type it in hit the save button it shows the error Case data invalid. On the other hand, it works well with the mobile app UI creating new cases. Please attend to this. Even if the creation of cases is basically the work of the mobile UI officers, the supervisors should have the administrative privilege to create a new case. Please let me know if this is not clear or you can test creating a new case on the web app UI.
![image](https://cloud.githubusercontent.com/assets/19344651/23120499/dc23cde6-f75c-11e6-950f-5258af50e9a0.png)
![image](https://cloud.githubusercontent.com/assets/19344651/23120533/faa9f844-f75c-11e6-824a-e441b528ae0f.png)

**Comment by MartinWahnschaffeSymeda** [comment]
Will be resolved with #118

**Comment by MartinWahnschaffeSymeda** [comment]
Fixed
