### ISSUE TITLE
Limit officer assignment to those of the LGA [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#125]
mentioned by @hzi-braunschweig: I am having serious synchronization issues with the contact app.
- assigning a contact to a contact officer of a source case who is not created by the contact officer
- viewing tasks associated with the contact officer with respect to the assigned contact person
- creation of new contact by contact officer and assigning to source case

**Comment by MartinWahnschaffeSymeda** [comment]
probably caused by the case being in another lga than the case.

- [ ] limit assignable officers to those of the lga

**Comment by MateStrysewskeSym** [comment]
NB: Talk about the roles today
