### ISSUE TITLE
Make formatting of dates consistent [0.5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#129]
All dates displayed should have the same format throughout both the webapp and the Android app.
- [x] update date formats: DD/MM/YYYY
- [x] make sure report dates display the time
- [x] make sure that dates on mobile and server are the same, when both use the same time zone

**Comment by StefanSzczesny** [comment]
- [ ] date of initial symptom onset
