### ISSUE TITLE
webapp starting pages

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#131]
Default site when opening webapp should depend on the user's role:

- [ ] surveillance sup - dashboard
- [ ] contact sup - contacts
- [ ] rumor off - events
- [ ] case sup - cases
- [ ] lab user - samples

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @stoikkanen @gstephan30 @Krisistis What do you guys think about these login pages
![webappuiv2](https://cloud.githubusercontent.com/assets/19344651/23830734/14f8ad98-0712-11e7-979f-6717466009cb.png)
![webapui_v1](https://cloud.githubusercontent.com/assets/19344651/23830733/14f8718e-0712-11e7-8b2a-404ed7708479.png)

**Comment by gstephan30** [comment]
Second looks good, but the left bar is redundant in live version? Still thinking about an hzi and/or symeda logo, but the login page should not be the yellow pages ;)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Yes the image was sent earlier to you. Please use the login page above with the map

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda From our discussion, to make the left side not to be redundant, you will add the following basic information on SORMAS

SORMAS stands for “Surveillance, Outbreak Response Management and Analysis System“
[]  To detect infection outbreaks without delay,

 [] To manage complex processes of infection control and containment and

 [] To ensure continuous analyses of the epidemiological situation.

Then as a footer you can have © 2017 SORMAS. All Rights Reserved.

**Comment by MartinWahnschaffeSymeda** [comment]
No longer relevant. All web app users will get a custom dashboard.
