### ISSUE TITLE
Button captions for create/edit view in integrated lists

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#136]
The "create" button should be renamed for the create/edit popups for PreviousHospitalization, EpiDataBurial, EpiDataGathering and EpiDataTravel (e.g. to "add") to better reflect the concept and indicate that the hospitalization/epidata still has to be saved.

**Comment by MartinWahnschaffeSymeda** [comment]
ther was no generic way to do it. it's "done" in all 4 components now.
