### ISSUE TITLE
App Exception Reporting [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#146]
We need a way to log errors into a file that users can send to us.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda  Yes, I was just thinking about what the best method would be? Because we would need same for the main workshop.  Do you have like a demo template for debugging and troubleshooting that we can use?

**Comment by MartinWahnschaffeSymeda** [comment]
Probably even better: Handle execeptions with google analytics https://developers.google.com/analytics/devguides/collection/android/v4/exceptions

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] integrate google analytics for error reporting
- [ ] move integration to config file. Specific account infos should not be commited
- [ ] make sure configuration would work with build server
- [ ] when the app is starting in the development environment exceptions should not be sent to GA
- [ ] uncaught exceptions need to be reported to analytics
- [ ] caught exception need to be reported if the exception is not expected (e.g. no ValidationExceptions)
- [ ] prepare exception handling refactoring: which types of exceptions are we using. What needs to be replaced.

**Comment by MateStrysewskeSym** [comment]
The property ID should be moved to a separate configuration file once the application goes live; it's not necessary beforehand. The final configuration file should never be committed to this repository (if possible).

**Comment by MartinWahnschaffeSymeda** [comment]
Config stuff has been moved to #195

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Try to find a way to handle uncaught exceptions to add the user uuid and possibly the stack trace

**Comment by MartinWahnschaffeSymeda** [comment]
See "Google Analytics in Deutschland datenschutzkonform einsetzen – so geht’s"

http://t3n.de/news/google-analytics-deutschland-822104/

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym The current implementation uses google firebase app indexing. We need to clarify if this is really needed and if so why.  E.g. AbtractRootTabActivity.getIndexApiAction doesn't provide a real URL.

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda We probably don't need app indexing at all because we don't want any contents of the SORMAS app to appear in Google anyway; indexing was part of the Gradle file before though, and version changes of other dependencies required this dependency to be updated to firebase indexing. I've completely removed it now.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] replace parameters of buildDescription method with Throwable
