### ISSUE TITLE
Task improvements (app)

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#151]
- [x] Task list: add name+disease of case/contact/event. For event use type + date + city + first part of desc. I have refreshed the moqups with a new layout: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a5763e1ae
- [x] Style notification accordingly: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a481defb9
- [x] Tasks tabs: blue line is missing -> don't use fixed width for tabs
- [x] Task notifications seem to popup for all users - not only the one responsible for the task

**Comment by MateStrysewskeSym** [comment]
Styling the notification as in the moqup is not possible because the notification icon is displayed to the left of the text (at least for some Android versions), which means that there is not enough space for a layout with two columns.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] update notification moqup
