### ISSUE TITLE
Case Symptoms fixes

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#153]
- [x] "Current body temperature in °C"
- [x] Section headline: "Recent symptoms" (web and app)
- [x] "Please answer for all symptoms whether they occurred during this illness."
- [x] App: Data is lost when required fields are not filled -> validate

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] update moqup
- [ ] edit layout according to moqup

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Moqups are updated:
app: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a1ca291bb
ui: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a24c618a7

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym Please look at this error 38.9 temperature not symptomatic- bug.. This is on the symptom page for contact visits. When a symptom is selected or a temperature greater than 38 is selected the status still reads "not symptomatic". Please note that the symptomatic or assymptomactic nature of the app should not only depend on the temperature greater than 38 degrees but once one symptom appears then the system should read its status as symptomatic. Is this clear? Thanks
