### ISSUE TITLE
Samples improvements

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#155]
- [x] show case disease in samples list
- [x] remove sample id in form and list
- [x] add "lab sample id" as own field (& update data dictionary)
- [x] move reporting user and date as a label to the right: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a2a53e848
- [x] lab form: save button should be at the bottom right of the editable form (not under the case information) -> do this by outsourcing the case info part
- [x] results form: time caption is not clear. Make form smaller and add "time" to caption
- [x]  results list: Type of test is display small instead of capitalized

**Comment by MartinWahnschaffeSymeda** [comment]
Additions:

- [ ] On the second scenario the creation of new sample results was not succesful and generated an error (saveSampleTest...)
- [ ] It is illogical that the user is allowed to enter a result for a sample which has not been received. As a suggestion, the “add a new result” –menu should be available only when “received” is selected (data quality control). 
- [ ] The “date of diagnosis of lab result” was thought to be too long and clumsy, maybe “Date of result” would be enough

@stoikkanen Can you tell me what caption we shall use instead of "result verified". I don't have it in my notes.

**Comment by hzi-braunschweig** [comment]
Hey Martin, @MartinWahnschaffeSymeda  "result verified by supervisor"

**Comment by MateStrysewskeSym** [comment]
Disease is alreay shown in the app list. Displaying it in the webapp grid is redundant because the disease is already specified on the same page.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] set fixed width for laboratory column (all samples list, UI)
