### ISSUE TITLE
Create/Edit visit for contact

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#16]
- [x] "+" create button in contact visits tab
- [x] New visit is assigned to the contact's person and has the same disease as the contact's case
- [x] VisitNewActivity, add to hierarchie in manifest
- [x] Create visit form layout based on mockup: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a4cea690b
- [x] Afterwards go back to where we came from (e.g. contact visits)
- [x] only contact officer is allowd to create visits

**Comment by StefanSzczesny** [comment]
code for role check is deactivated
