### ISSUE TITLE
Up button behavior for notifications

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#160]
When a notification is received and the associated task opened from it while the app is not open, the app will close when tapping the "Up" button. The user should get re-directed to the task list instead. Also, when accessing the task from a notification while the app is opened, tapping the Up button to go back to the task list unwantedly opens the main menu.

**Comment by MartinWahnschaffeSymeda** [comment]
This is already working now.
