### ISSUE TITLE
Caption fixes/renaming

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#173]
- [x] "Assignee reply -> "Comments on execution"
- [x] "Phone" -> "Phone number"
- [x] "Date of symptom onset" -> ???

EpiData
- [x] rename "Contact" to "Exposure" for all fields associated with animals
- [x] "Date of contact" -> "Date of last exposure"
- [x] "Place of contact" -> "Place of last exposure"

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda what should "Date of symptom onset" be renamed to?

**Comment by MartinWahnschaffeSymeda** [comment]
It should be renamed to "Date of symptom onset". Currently its called "Date of initial symptom onset"
________________________________
Von: MateStrysewskeSym [notifications@github.com]
Gesendet: Mittwoch, 5. April 2017 08:38
Bis: hzi-braunschweig/SORMAS-Open
Cc: Martin Wahnschaffe; Mention
Betreff: Re: [hzi-braunschweig/SORMAS-Open] Caption fixes/renaming (#173)


@MartinWahnschaffeSymeda<https://github.com/MartinWahnschaffeSymeda> what should "Date of symptom onset" be renamed to?

**Comment by MateStrysewskeSym** [comment]
Okay, thanks!
