### ISSUE TITLE
Other adjustments/fixes

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#174]
- [ ] Allow users to unset radio fields by clicking on the selected value again

**Comment by MartinWahnschaffeSymeda** [comment]
Adjust scss for grid tables:

- [ ] change .sormastheme .v-grid-cell font-size to 13px
- [ ] change .sormastheme .v-grid-header th font-size to 12px

**Comment by MartinWahnschaffeSymeda** [comment]
Left todos are not needed for tomorrow
