### ISSUE TITLE
Case adjustments/fixes

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#175]
- [x] Hide "Possible case" classification from Hospital Informants and rename it to "Not yet classified"
- [x] Allow officers to edit the case classification
- [x] Remove EpiData headings when they contain no items
- [x] "Exposure to sick poultry" should only be shown when "Exposure to poultry or domesticated birds" is set to "Yes"
- [x] Add "clear all" and "set all to no" buttons above symptoms
- [x] Turn "First symptom" to a spinner field containing all symptoms that have been set to "Yes" (done for WebApp, needs to be done for Android)

**Comment by MartinWahnschaffeSymeda** [comment]
Left todos are not needed for tomorrow
