### ISSUE TITLE
Task adjustments/fixes

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#176]
- [x] Make comment field required for "Other task as specified in comments"
- [x] Add address of the case/contact/alert to the task form (app)
- [x] Enable the "Contact tracing" task type for cases

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] please make sure that in the main tasks activity (not the one for a single case or contact or alert) only tasks that are assigned to the user are shown
