### ISSUE TITLE
Contact adjustments/fixes

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#177]
- [x] When "Lives in the same household" is selected, the contact person's address should automatically be set to the one of the case if empty
- [ ] Make address a required field (I'd rather not do this for the moment and instead discuss it again because we need to figure out which of the address fields can actually be made required)
- [x] Add "Convert to case" button that automatically switches the status to Converted to case to the webapp
- [x] same for android
- [x] Allow the creation of a case from a contact from the contacts list
- [x] make first and last name read-only, don't display the person select or create window when creating a case from a contact
- [x] Add contact follow-up generation for Avian influenza (17 days)
- [x] Don't show disease in follow-up visits list (webapp), but rather in the info box in the top right -> leave disease in list, because the person may have had visits for different diseases
- [x] Fix a crash that happens when saving a contact again after the validation failed
- [x] Fix an issue where a visit cannot be created because of a NullPointerException -> this happened when a new visit was created for a disease that did not have a follow-up until time

**Comment by MateStrysewskeSym** [comment]
I just realised that, when creating a new case from an event participant, the name and address weren't filled with the respective values from the event person. This has been fixed, and in addition, the name and disease fields are now read-only to make sure that a correct case is created.

**Comment by MartinWahnschaffeSymeda** [comment]
Left todos are not needed for tomorrow
