### ISSUE TITLE
Lab samples adjustments/fixes

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#178]
- [x] Make "Lab sample ID" a ready-only label in the app
- [x] Create a "Sample source" enum for use with Avian influenza: Human, Animal, Environment
- [x] Add a "Suggested type of test" field to the creation of a sample
- [x] Make sample details that don't make sense to edit after the shipping read-only for Lab Managers; find a way to set "Not shipped" and "Shipped" to read-only as well

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] if possible don't show "lab sample id" at all in the sample creation form of the app

**Comment by MartinWahnschaffeSymeda** [comment]
Left todos are not needed for tomorrow
