### ISSUE TITLE
Setup and update guide

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#179]
There is already a guide that explains how to setup the development environment.
This needs to be updated with information on how to update a server without using eclipse.

- [x] guide that explains how to setup the domain
- [x] guide that explains how to update the domain

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 I have updated the SORMAS readme with a guide on how to setup and update a local server:
https://github.com/hzi-braunschweig/SORMAS-Open/tree/development

Please have a try using this and setting up your own server.

**Comment by gstephan30** [comment]
@MartinWahnschaffeSymeda can you add a SORMAS pic in the readme, and highlight or add some code in the readme (eg. "git config --global branch.development.rebase true" - should be marked as code) @dta16 maybe you/we can make some screenshots how we set it up and add them to the readme?

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 If you have create screenshots it would be great if you could add them to the readme.
