### ISSUE TITLE
"not executable" status for tasks

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#18]
- [x] add status in sormas-api TaskStatus
- [x] make sure web-ui relfects the changes
- [x] add "not executable" button to TaskEditActivity (see https://app.moqups.com/symeda/3NUENEwuOE/edit/page/af894caab)
- [x] add "not executable" filter tab in TasksActivity

**Comment by MartinWahnschaffeSymeda** [comment]
We probably need a filter "pending or not executable" for the tasks list

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] officer app: reason is required when setting task to not executable

**Comment by StefanSzczesny** [comment]
see #36
