### ISSUE TITLE
App should synchronize incoming changes before sending data [8]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#190]
When two users are editing data of the same case at the same time (which can often happen, due to
the offline capabilities of the app), the synchronization process has to merge those changes so loss of
data is reduced to a minimum.

- [x] keep a copy of the original entity, when saving changes. Set the "modified" flag to true, to distinguish
- [x] create a copy of all embedded domain objects as well
- [x] getByUuid should only return the working version
- [x] add additonal method to retrieve copied original version
- [x] unify pull createOrUpdate logic
- [x] send modified version to server and drop it, after the server has accepted (-> accept method for dao)
- [x] server should only accept data from the app when the app has the latest version from server (based on change date)
- [x] make sure modified entries don't appear two times in lists

App retrieves data from server and merges changes: 

- [x] Unify the way entities and dtos are created in the app
- [x] Check differences between local unmodified and server version. Try to find the most generic solution for this.
- [x] Write each difference into local modifed (if existent). Override changes
- [x] Handle "send data too old" with explixit exception

Deal with lists

- [x] automatically detect lists of EmbeddedAdo
- [x] add parent info to list elements
- [x] handle saving and merging automatically

Try the implementation for the samples entity first. The [+X] is the implementation for all other entities

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym I have finally managed to implement this stuff. I have some merge conflicts we need to solve, before I can commit this (the problem mentioned in #207). 

In addition we have to make sure that synchronization is not done while the user is editing data. This would lead to a second merge layer that would be even harder to implement and more error prone.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] document the current merge behaviour
- [ ] create basic unit tests

**Comment by MateStrysewskeSym** [comment]
When editing a case in the webapp/mobile app at the same time, I had the following problem:
- Save the case in the webapp
- Save the case in the mobile app
- Edit and save the case in the webapp again without leaving the page

In this case, the case will not be saved, but an error will be thrown saying "Dto is older than existing entity". This should not happen.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] display error message when trying to save an entity in the web app while the same entity has been changed by someone else
- [ ] make sure that no entities are displayed twice in the app when no internet connection is available and entities are changed
- [ ] resolve the dto sync problem by correctly checking change date on the server side (probably previous hospitalizations)

**Comment by MateStrysewskeSym** [comment]
- [ ] Had a situaion where the app failed accepting a modified case, because it had an burial that didn't have a snapshot created (and set to modified), though the burial likely existed before.

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda Your most recent changes result in constant crashes when the server is offline, even if the app isn't opened

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] mergeCollection method currently deletes new entries, when a changed version is sent from the server

**Comment by MartinWahnschaffeSymeda** [comment]
See #220 , #216 #221
