### ISSUE TITLE
Epi Curve Week and Month Grouping [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#198]
- [x] Add on option to select groupings (dropdown): day (default), epi-week (like calendar weeks), month - either add additional options (e.g. epi-week (minimum of 7) or checkboxes to toggle additional entries
- [x] Add an expand option
- [x] fix height difference between the two buttons
- [x] remove text from expand/collapse button to provide more space for more useful elements
- [ ] ~~change style of numbers on bars~~

**Comment by MartinWahnschaffeSymeda** [comment]
We need to clarifiy what grouping should be used by default. It might make sense to do per week by default and show additional previous weeks

**Comment by hzi-braunschweig** [comment]
Per week by default is a better option and then show additional previous weeks.


Regards

Tom-Aba Daniel (B.Sc MPH)
Department of Epidemiology
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de<mailto:Daniel.Tom-aba@helmholtz-hzi.de>
EXT: 05316181-3124

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] change week caption to epi week
- [ ] add first three letters of years and "Wk" (without slash) for weeks to labels and date filter
