### ISSUE TITLE
Users of the mobile app login with username and password once [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#202]
- [x] create login screen that allows to enter username and password
- [x] credentials (user name + password) are stored in the android keystore
- [x] active user in ConfigProvider should be based on keystore instead of database
- [x] In order to assure the safety of stored user credentials android device encryption has to be activated. If possible check this and otherwise refuse to work
- [x] add a log out button to the user screen that deletes the credentials and opens the login page
- [x] uncomment the user select
- [x] add option to show settings, so the url can be changed

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda we need to discuss whether it's a good idea to store the password on the phone, even if it's encrypted; alternatively, we could use an authentication token that is encrypted and stored in the SharedPreferences, gets sent with every request and is automatically invalidated when the password changes.

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda Synchronization now fails when the app is closed; please look into that. Could be the same problem like the one I just fixed.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] don't select settings in navigation menu

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make logo bigger

**Comment by MartinWahnschaffeSymeda** [comment]
See https://github.com/hzi-braunschweig/SORMAS-Open/issues/219

**Comment by MartinWahnschaffeSymeda** [comment]
Fixed problem with AlertDialog. Now called in LoginActivity
