### ISSUE TITLE
Data change audit log [2+X]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#207]
For the purpose of data security all changes made by users have to be written to an audit log.

This includes the following information:
* Who was changing data (user)
* When was the data changed (time)
* What data was changed (field and value)

The data log will be created in a way that makes it queryable. This means it is possible to get all log information for a single entity (e.g. a case) using an SQL query.

Note: This does not include a user interface to access the information about changed data

- [ ] define what exactly needs to be done
- [ ] create database (sormas_audit_db)
- [ ] connect the database to the server

**Comment by MateStrysewskeSym** [comment]
**Important:** The max_prepare_connections value in the postgresql.conf has to be set to at least the number of max_connections!

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
You have added dependencies to java 8 (time) to sormas-api, but the project is only java 7. A solution might be to move the corresponding methods to sormas-backend. In addition we should make sure that your eclipse is configured correctly - it should have shown the problem.

**Comment by MartinWahnschaffeSymeda** [comment]
I have create an update batch script

[glassfish-config-update-audit.bat.txt](https://github.com/hzi-braunschweig/SORMAS-Open/files/1035922/glassfish-config-update-audit.bat.txt)

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym We need to find a way to document (and/or validate) the needed change of the postgreconf.

**Comment by MateStrysewskeSym** [comment]
See #212
