### ISSUE TITLE
Automatic auditing of members for @Audited entities [2]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#209]
Things to exclude by default: 
- [x] @Transient
- [x] @AuditedIgnore (needs to be implemented)
- [x] reference annotations (@OneToOne, @OneToMany, ...) that are mapped by another class. If this task takes too much time, we should discuss again whether it is really needed.#
- [x] take existing unit tests
- [x] add new unit tests that check the annotation behaviour

Keep @AuditedAttribute and @AuditedCollection (used when specific value formatter is needed)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] refactor code in getAuditedAttributes (useless for loop)
