### ISSUE TITLE
Automatic release with jenkins git flow

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#215]
Basic information:
See https://dzone.com/articles/why-i-never-use-maven-release
and https://danielkummer.github.io/git-flow-cheatsheet/

Releases should be done with a jenkins build that automatically changes the version, handles branching and tagging in git, etc.

I'm not sure what implications the existance of the sormas android app (gradle) has on this. Maybe jgitflow already supports it.

- [x] change the version in maven: sormas-base/pom.xml and all depending projects
- [x] change the version in gradle: sormas-app/app/build.gradle 
     android.defaultConfig.versionName matches maven version
     android.defaultConfig.versionCode just needs to be incremented
     update sormas-api dependency in the dependencis section)
- [x] create release branches and tags (use git flow defaults if that makes sense)
- [x] document how new releases of sormas are released on developer side.

**Comment by MartinWahnschaffeSymeda** [comment]
See https://dzone.com/articles/why-i-never-use-maven-release

**Comment by StefanKock** [comment]
I think Martin points out a very important point: The maven-gradle-integration (#183) is most likely needed for this.

**Comment by StefanKock** [comment]
I started integrating the _jgitflow-maven-plugin_ (https://bitbucket.org/atlassian/jgit-flow) and configuring it for an automatic release process.

**Comment by StefanKock** [comment]
To solve the problem which credentials to use by jgitflow-maven-plugin this website gave a good hint: https://stackoverflow.com/questions/36189877/maven-jgitflow-plugin-authentication-for-https

**Comment by StefanKock** [comment]
I combined successfully sormas-app/pom.xml an sormas-app/build.gradle. Gradle now gets the sormas Version out of the Maven POM and calculates automatically a versionCode.

TODOs for finishing this ticket:
- Test new sormas-app in Android Studio
- Merge my branch from the fork to development

**Comment by StefanKock** [comment]
Successfully tested with android studio and merged into development
