### ISSUE TITLE
Improved sample testing process (POS 2) [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#229]
Entity/logic:
- [x] Calculate shipment status in the backend when saving the sample

UI: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a2a53e848
- [x] Shipment status should be split into a "shipped" and "received" checkbox
- [x] Core and shipment data can only be entered by the user reporting the sample
- [x] Move report information into sub header (see mockup)
- [x] Adjust layout to match mockup
- [x] Make disabled fields unrequired

App: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a780f96e8
- [x] Replace shipment checkbox logic
- [x] Add "Received" section
- [x] Move "comments" textbox

Sub-issues: #254 #255

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] create mockup

**Comment by MateStrysewskeSym** [comment]
- [ ] keep ShipmentStatus instead of shipped/received booleans and add a unit test instead to make sure that future changes to the code/enum don't break the logic.

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
I had to re-rename the app columns, because renaming doesn't work with SQLite as well. Might be necessary for you to drop your data again.
