### ISSUE TITLE
Automatic generation of EPID-number prefix (POS 1) [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#230]
The first part of the EPID-number should be generated by the system when a case is created. 
The EPID-number is made up of the following parts: CountryCode-StateCode-LGACode-YY- (Example: NIE-KN-AJ-17-). The user only adds the sequence number for the LGA.
In order to do this the two-letter codes for country, region (state) and district (LGA) have to be added to the system.

sormas-backend
- [x] make state and lga codes available

sormas-api
- [x] add method to check if epid-number is complete
- [x] add method to check epid-number format
- [x] add method to create epid-number-prefix that is used when a case is created

sormas-app
- [x] add validatior using api methods

sormas-ui
- [x] add validatior using api methods

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Where can I find the two-letter codes for states and LGAs? Neither the health facility files, nor the shape files contain them.

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Is the two- or three-letter country code used? (NG or NGA)
Any progress on the state and LGA codes?

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
The AMPACODE column seems to contain the country, state and lga codes. It's probably best to split this into three columns. SN, GoeZones and LGHMCODE can be dropped.
I suggest to import the file whenever there is a region that has no code.

[coded_states_lgas.xlsx](https://github.com/hzi-braunschweig/SORMAS-Open/files/1170090/coded_states_lgas.xlsx)

**Comment by MateStrysewskeSym** [comment]
A lot of districts and two regions are spelt differently in the .xlsx file and the .csv region files we've received. It's crucial that the spelling is absolutely consistent. We need to find a way to assure this.

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
I have added the LGA names that we are currently using in the system in an additional column.
Import should be done based on that new column.

[coded_states_lgas.xlsx](https://github.com/hzi-braunschweig/SORMAS-Open/files/1173144/coded_states_lgas.xlsx)

**Comment by MateStrysewskeSym** [comment]
- [ ] Split epid code and add respective fields to region and district

**Comment by MateStrysewskeSym** [comment]
It's the epidemiological number that is assigned as an identifier to every case in the Nigerian and a lot of other health systems.

**Comment by bernardsilenou** [comment]
EPID number = unique identifier of a case per disease = country code-region code-district code-year-case series number
