### ISSUE TITLE
Import health facilities of all 36 states of Nigeria and the FCT [0,5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#237]
@dta16 
- [x] for each state create a csv having the state's name (e.g. Kano.csv) based on the following format:
    LGA;Ward;Settlement;Facility;Type;Ownership;Address;Longitude;Latitude
    See https://github.com/hzi-braunschweig/SORMAS-Open/blob/development/sormas-backend/src/main/resources/facilities/Oyo.csv

Symeda:
- [x] add csv files to backend and import the states
- [x] check how long first sync takes. Might be necessary to check if the merge process has a negative effect on this

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 
Please add the two-letter codes for the LGAs as well.
Prefereably: LGA;LGA2;Ward;Settlement;Facility;Type;Ownership;Address;Longitude;Latitude

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda I have uploaded some csv files as requested. I hope you dont mind. I had to combine some states together while exporting and uploading. I have uploaded them to the facilities repository

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda See attached file for coded states and LGAs.
[coded_states_lgas.xlsx](https://github.com/hzi-braunschweig/SORMAS-Open/files/1158060/coded_states_lgas.xlsx)

**Comment by MartinWahnschaffeSymeda** [comment]
For performance issuses see #248
