### ISSUE TITLE
Generic Health Facility option (Other_Health_Facility) [1]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#238]
@MartinWahnschaffeSymeda @gstephan30 @MateStrysewskeSym To enhance the flexibility of managing any outbreaks at the moment, please add to the health facility drop down on the mobile app and web app, the following:
[ ] a generic option may be called "Other" so that if in an event that the health facility is not registered within SORMAS app then the user can select the option "Other" and enter in a text field, the name of the new health facility.
[ ] When the facility management console is ready, then the supervisor or super admin can filter all "Other" health facilities and assign them to SORMAS as part of the health facilities within SORMAS. 

[ ] Added to issue #237, we should add all primary health care facilities for each state in Nigeria so as to minimise these kinds of entries.

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Adding only the hospital name will lead to the situation that we can't show the case in the dashboard map, because we don't have gps coordinates for the facility. 
An alternative would be to use the report gps coordinates, but then we still have to group this somehow in the map.
How should we handle this? Is it ok, if cases don't appear in the map until they have been assigned to a "real" facility.

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 In addition it's maybe best to call the field "Facility description", so informants can provide name and other details that might be relevant to understand what kind of facility it is and why it's not in the system yet.

**Comment by MartinWahnschaffeSymeda** [comment]
Implementation:

- [ ] Add a health facility called "Other facility" to the facilities list (no region). Use a fixed UUID that is accesible as a constant
- [ ] Add the health facility on top of every health facility query result (independent from region, etc.). Not for laboratories
- [ ] When "other facility" is selected, display a text field "Facility name & description"

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Please ignore the migration for this ticket. Simply increase the database version and keep droping the database. We will include the migration process when we add the lab stuff.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @gstephan30 @MateStrysewskeSym @Krisistis  Yes, I was thinking about it. But as is currently done on existing systems, geo cordinates are created based on Case creation. So wherever the case is created, whether in the health facility or at home, the report location should be geo coded. For grouping, I'd say we group by LGAs and show them as geo points on the case map based on location. Now on the case map filter, you can toggle map and filter by actual case location and actual case location in health facility. This would solve the problem of now been able to allocate a new health facility when created. So when the case who belongs to the Other_health facility has been reclassified and the new facility with its description entered, then the case is automatically added to the actual case location in health facility. This works the same for Event map and Alert map as well. Please let me know if you have any questions.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Other health facility is show as "null" in app

**Comment by MartinWahnschaffeSymeda** [comment]
Refactorings in app and backend
- [ ] getAllByfacilityType -> getLaboratories (never include "other")
- [ ] getAllByCommunity/District (NOT region) -> getHealthFacilitiesByCommunity/District (always include "other")
- [ ] user getByUuid to include "other" facility in result list
