### ISSUE TITLE
Synchronization optimizations [0,5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#239]
- [x] don't sync when saving within case - instead sync when case is left
- [x] don't sync in background while working inside a form
- [x] when resuming an editing activity check whether the edited entity has changed in between (changeDate). 
- [x] if the entity has changed reload it as done in onCreate method - maybe extract load/init logic to a separate method
- [x] show a snackbar to the user "Case refreshed. Unsaved changes have been discarded"

**Comment by MateStrysewskeSym** [comment]
- [ ] Cases aren't pulled when only the person has been changed on the server
- [ ] Events aren't pulled when only the event location has been changed on the server (this might be the case elswhere, too)
- [ ] Visits aren't pulled when only the symptoms have been changed on the server

**Comment by MartinWahnschaffeSymeda** [comment]
- [x] do first sync in PinActivity.onCreate instead of LoginActivity.onCreate
