### ISSUE TITLE
Case label in task activity should link to case

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#24]
When the user open's a task in the app it should be possible to jump to the associated case.

- [x] Open case on click
- [x] Redesign label to make obvious that it's a link
- [ ] Make sure that the user is redirected back to the task when clicking the back button

Sprint 10 review:
- [x] make link method on labelField and give ClickListener as param

**Comment by StefanSzczesny** [comment]
see #54 for backnavigation
