### ISSUE TITLE
Add form validation to android app [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#241]
Needed for #230 
- [x] Have a look into android reference on how validation is done
- [x] find a way to add a validator to a field or do validation in the form. Update whenever field value changes
- [x] show validation message below field
- [x] if needed it should be possible to save anyway (e.g. EPID-number)
- [x] find a way to visually make clear which fields are required

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] use static method to return lists in SymptomsValidator
- [ ] make validator classes final
- [ ] add listener to labels that close error popups on click
- [ ] add required indicators (add method to validators)
- [ ] add clearError method to PropertyField (should not focus)

**Comment by MateStrysewskeSym** [comment]
The required indicators still have to be added to the Symptoms tabs, but this is more complicated than in the other cases and I don't want to postpone the deployment of the new version for any longer.
