### ISSUE TITLE
Moqups for Infrastructure Administration [0,5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#244]
see #232 

- [x] New main section "Infrastructure"
- [x] Tab "Facilities" that lists facilities and allows creating, editing and archiving
- [x] Tab "Regions" / States
- [x] Tab "Districts" / LGAs, region as filter
- [x] Tab "Community" / Wards, region and district as filter
- [x] check if other filters are needed for each of the tabs

**Comment by MateStrysewskeSym** [comment]
See https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a39f20492

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym We need a way to show archived regions. E.g. a link button called "show archived entries" below the table. Should only be visible when there are archived entries. When clicked it could be replaced with a link button called "show active entries".
