### ISSUE TITLE
Show help-text when user taps a field's caption

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#25]
When the user taps the caption of a field a pop-up with the field's description should be shown.
This should be implemented for all our custom fields (PropertyField).

**Comment by MateStrysewskeSym** [comment]
Do we need a visual indicator hinting at the case that a label has a help text associated with it?

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym It would be a good feature to have,

**Comment by MateStrysewskeSym** [comment]
Visual indicator added, needs discussion.
