### ISSUE TITLE
Task execution buttons don't show

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#257]
To Reproduce try to use two phones: Report a new case with the informant and see if the officer gets the task and can execute it.

**Comment by MateStrysewskeSym** [comment]
We couldn't reproduce this error; it might have been already fixed, but just to make sure, I'm moving this to Sprint 23 in case it reoccurs.

**Comment by MartinWahnschaffeSymeda** [comment]
Happened with Informant on my emulator
