### ISSUE TITLE
Allow users to assign case to no health facility [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#261]
- [x] add new static health facility named "None" (see #238)
- [x] give healthFacilityDetails field a more generic caption or let the caption be dependant on "none" or "other" being selected
- [x] show cases in dashboard map using reporting GPS coordinates (see #86)
- [x] do the same for cases with "other" health facility
- [x] use another marker to distinguish cases from health facilities
- [x] "Other" and "None" should be shown at the bottom of the facility list
- [x] add a button to display cases without a GPS tag (e.g. 'Other'/'None' facility set and no report geo coordinates)

**Comment by MateStrysewskeSym** [comment]
- [ ] discuss how the case markers should look and create .svg files

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
I have created another marker style for facilities. We should have a look at this together tomorrow.

- [ ] rename button in dashboard to "cases without ..."
- [ ] add new columns to history tables as well

**Comment by MateStrysewskeSym** [comment]
- [ ] put NONE_FACILITY... as static variable in forms

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Rename to "Not a health facility" and "Other health facility"
