### ISSUE TITLE
Password generation problems

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#268]
The changes made to the password generation (not allowing the letter 'O' and the numbers 0 and 1) have lead to serious problems with resetting passwords, apparently resulting in empty spaces being added to the generated passwords that in turn produce a PSQLException when persisting them. It's possible that this also occurs with the former implementation (which has been restored for now), but more rarely because only the letters 'l' and 'I' are replaced there. We have to investigate this and make sure that our password generation algorithm is free of any errors, because this can lead to users being unable to use SORMAS after they have received a new password.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym  Also, it is important to have the generated passwords automatically sent to an email address or as an SMS to the user as copying the password directly from the screen is not sufficient. This is a major complaint from the user side. 

Thanks

**Comment by MateStrysewskeSym** [comment]
- [ ] fix code problems
- [ ] add unit test
