### ISSUE TITLE
Keyboard often stays open when navigating through form

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#27]
Example in case person form:
When you enter the last name field and use the "next" button of the keyboard the spinner for the gender doesn't open and the keyboard stays open.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @StefanSzczesny  We need to find a solution to this problem for the mobile app

**Comment by MateStrysewskeSym** [comment]
Found possible solution for the issue that the soft keyboard doesn't disappear when a spinner is selected; usage of "next" button is still broken though

**Comment by MateStrysewskeSym** [comment]
"Next" button now behaves as expected and can also select spinners and date fields.
