### ISSUE TITLE
Import health facilities, wards, lga, states for Oyo and Kano [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#28]
- [x] Make the data provided in xls-files located in ../SORMAS/Test data available as resource in server
- [x] Import complete data
- [x] Remove data of Abia

**Comment by hzi-braunschweig** [comment]
Martin, I have sent you a dropbox link for the complete data for all the states down to ward level. @MartinWahnschaffeSymeda @StefanSzczesny @MateStrysewskeSym

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda It is important to have the state and LGA filters activated on all the case and contact management instances to help narrow down search request or new contact or case task request. Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Can you please provide a list of all labs for both states? If you don't have a complete list it's ok. It should be all the labs we want to have in the system for the prototype.

**Comment by MartinWahnschaffeSymeda** [comment]
We decided to go with Kano only.

**Comment by MartinWahnschaffeSymeda** [comment]
@StefanSzczesny @MateStrysewskeSym @dta16 
Kano import is ready. Note that ALL DATA (even users) will be dropped with the update.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda  Roger that! Cant wait to see Kano Import
