### ISSUE TITLE
SMS gateway for notifications [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#292]
- [x] list possible options that allow to send an SMS from the SORMAS server to officers/informants

**Comment by MartinWahnschaffeSymeda** [comment]
* Essendex: Java API , ISO 27001, 7-8 cent per SMS https://www.esendex.de/business-sms-gateway?ls=PPC&sc=Google.DE&sd=sms%20gateway%20exact&gclid=CjwKCAjwrO_MBRBxEiwAYJnDLFlSTR2ERpsLcNhJILzxLgoWVnxfA12CPmElokUxTQddpGKbbF-hnhoCGKgQAvD_BwE

**Comment by MateStrysewskeSym** [comment]
- [ ] send current emails also as SMS to supervisors
- [ ] send tasks to be started or due as SMS to informants/officers (following same rules as notifications in app)

**Comment by MartinWahnschaffeSymeda** [comment]
In addition to receiving an email, users of the web app need to receive an SMS notifications for certain trigger events. This will inform them that something important happened in SORMAS and needs their attention. SMS is required, because it is much more common for users than email and can also be received in areas without data connectivity.

Implementation:

- [ ] Create a test account for nexmo
- [ ] Create a unit test that can send SMS using their service
- [ ] Send SMS whenever an email is sent to a supervisor
- [ ] Inform HZI to create an account
- [ ] add user settings "Send e-mail notifications" and "Send SMS notifications" (CheckBoxes - each unser the corresponding data field)

**Comment by MateStrysewskeSym** [comment]
- [ ] replace DeliveryExceptions with NotificationDeliveryFailedException, MessageType as parameter

**Comment by MateStrysewskeSym** [comment]
- [ ] don't send SMS and emails to users that initiate the respective action

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym  So I have created a nexmo account. the API key is 3f1d790f  , user name is SORMAS SORMAS. Whatelse do you need from me to activate the nigeria server?
