### ISSUE TITLE
Contacts do not appear for Contact Supervisor [0.5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#296]
When creating a contact in the Android app, Contact Supervisors don't see them in their list. Could have something to do with a missing user role in the user filters.

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig I couldn't reproduce this bug; are you sure that the Contact Supervisor in your test scenarios had the same LGA assigned as the cases you created contacts for?

**Comment by MartinWahnschaffeSymeda** [comment]
When a case is moved to another LGA the contacts of the case might not be transferred. They will be transferred when complete sync is done, though.

We need to find a way to detect this situation, so we can do the complete sync.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] do full sync whenever a case is sent to the app that currently is not in the app's database
