### ISSUE TITLE
Contacts disappearing after first sync after creation

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#298]
When creating contacts as a Surveillance Officer, they sometimes disappear after the first subsequent synchronization.

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Have you re-assigned the cases associated with these contacts while creating the contact? I can't reproduce this error and will need further information on how and when it happened.

**Comment by MartinWahnschaffeSymeda** [comment]
Is very likely related to #318 and fixed.
