### ISSUE TITLE
Contact app backend

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#3]
- [x] Copy contact entity from sormas-backend
- [x] Adjust annotations to ORMlite
- [x] Update DatabaseHelper init/update logic, database version++
- [x] DAO service and entity sync

**Comment by MartinWahnschaffeSymeda** [comment]
Visits backend and contact modifications are implemented and pushed (see #10). Please get the latest version and update the app Contact entity accordingly.

**Comment by StefanSzczesny** [comment]
#3 - Contact Entitiy and annotations, DAO, DTOHelper, Retrofit sync task, update database helper
