### ISSUE TITLE
Create mockups for sample testing (lab persona) [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#30]
* person in hospital will send lab material physically (probably informant)
* at the same time enters sample data into the system
* UID of system + another UID from the lab form
* lab person receive sample and has to match it to entry in sormas
* enters lab result for the sample
* list of test typs: relevant disease, result options
* list of labs with definition of test types
* possible 2 step process: forward to another lab
* multiple tests per sample

* sample: UID, Text-ID, Sample referral (lab), 2nd level sample referral, kind-of material + other, date+time of sampling (collecting), timestamp of shipment, shipment details, status: Shipped, Received & Pending, Further testing, Referred to other lab, Tested
* test: kind of test, date+time, lab, result (depends on kind of test; can also be text) + text-field, verified (user has to enter verification pin)

- [x] App Sample list in case: https://app.moqups.com/symeda/3NUENEwuOE/view/page/a628db1d7
- [x] App Sample list: https://app.moqups.com/symeda/3NUENEwuOE/view/page/a90a1bc36
- [x] App Sample create/edit: https://app.moqups.com/symeda/3NUENEwuOE/view/page/a780f96e8
- [x] Web-UI Sample list: https://app.moqups.com/symeda/3NUENEwuOE/view/page/adc9a738c
- [x] Web-UI sample list in case: https://app.moqups.com/symeda/3NUENEwuOE/view/page/afc481082
- [x] Web-UI Sample create/edit: https://app.moqups.com/symeda/3NUENEwuOE/view/page/a2a53e848
- [x] Web-UI Sample Tests list: https://app.moqups.com/symeda/3NUENEwuOE/view/page/a2a53e848
- [x] Web-UI Sample Tests create/edit: https://app.moqups.com/symeda/3NUENEwuOE/view/page/a6f3132e2
- [x] DataDictionary Sample, SampleTest

**Comment by MartinWahnschaffeSymeda** [comment]
First draft: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a780f96e8

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 @stoikkanen Can you update the data dictionary with the following please (https://docs.google.com/spreadsheets/d/1BA_RjM-ZhxFrzpAJdv0UVGhicHXNP6JnPBA-xzdrQKs/edit#gid=420561838)
- [ ] a list of sample materials (Line 22: SampleMaterial)
- [ ] a list of sample test types (Line 32: SamleTestType)
- [ ] which sample materials, tests and test results are valid combinations

**Comment by hzi-braunschweig** [comment]
@gstephan30  @stoikkanen

**Comment by MartinWahnschaffeSymeda** [comment]
All moqups are ready for implementation now.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Hey martin, I don that have access to see your appmoqup links. The only link i can access is the mock ups you gave me access to initially. Please can you give me access. Thanks

**Comment by hzi-braunschweig** [comment]
![image](https://cloud.githubusercontent.com/assets/19344651/22333770/06c04acc-e3d8-11e6-85bf-fae27e945bf8.png)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda

**Comment by MartinWahnschaffeSymeda** [comment]
I have added links to the list above

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] update moqups based on "shipment status" changes
