### ISSUE TITLE
E-mail notification for supervisor (task, lab result, symptomatic, case classification) [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#31]
Supervisors should receive notifications for specific events via e-mail so they (1) have a trigger to look into SORMAS and (2) don't miss important news.

Trigger events:

- [x] task is to be started or due (supervisor + national)
- [x] lab result comes in (case & surveillance)
- [x] contact becomes symptomatic (contact & surveillance) - following the same rules as the "symptomatic" column in visits directory
- [x] case classification changed (case, contact & surveillance)

Tasks:

- [x] build a service that can be called when an event happens
- [x] service handles sending an email (and/or SMS later)
- [x] define texts for all events. Ideally these should be short, so they work as SMS as well. OR: Provide a short and a long text (with link).
- [x] call the service from the above triggers (from facade)
- [x] for tasks add a timed method that checks for due tasks (see app for logic)
- [x] create e.g. onCaseChanged method that contains email logic and method calls such as updateInvestigationByStatus etc.

**Comment by MateStrysewskeSym** [comment]
- [ ] add test result type to labResultArrived and labResultSpecified messages
- [ ] change subject from "Lab result changed" to "Lab result specified"
- [ ] split task messages (general or entity specific)
- [ ] change taskDue message to "%s task (for %s) is overdue." -> add keyword (e.g. "case") and short uuid for entities
- [ ] rename taskNew and taskNewSubject to taskStart and taskStartSubject
- [ ] change taskStart message to "%s task (for %s ) should be started."
