### ISSUE TITLE
DaoException saying that a sync was done between reading and saving entity

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#310]
de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:246 -> de.symeda.sormas.app.caze.CaseEditActivity:onOptionsItemSelected:340

de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:246 -> de.symeda.sormas.app.backend.epidata.EpiDataDao:saveAndSnapshot:74 -> de.symeda.sormas.app.backend.epidata.EpiDataDao:saveAndSnapshot:18 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshotWithCast:171 -> de.symeda.sormas.app.backend.common.AbstractAdoDao:saveAndSnapshot:223 -> de.symeda.sormas.app.caze.CaseNewActivity:savePersonAndCase:206

**Comment by MartinWahnschaffeSymeda** [comment]
Was related to #304
