### ISSUE TITLE
Event map on supervisor dashboard

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#316]
Rumor events should be display in the supervisor dashboard map (in addition to the visualization of contacts and cases). The coordinates are taken from the location of the event (see POS 5). If no coordinates exist the centroid of the associated district (LGA) is used.

See also #126

**Comment by MateStrysewskeSym** [comment]
Discuss: Display events by Rumor/Outbreak or only rumors by classification?
