### ISSUE TITLE
Make app "+" buttons for lists better touchable and add empty list call to action [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#339]
- [x] App "+" buttons for lists are too small, E.g. burial "+" button doesn't work very good - maybe add "add" label
- [x] In addtion: For lists e.g. show "please add prev hosp" notification when "yes" is set

**Comment by MateStrysewskeSym** [comment]
The ValueChangeListener of the AbstractTableField does not trigger when items are added to or removed from it.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] add null check to epi data sublists (as already done for previous hospitalizations)
