### ISSUE TITLE
Missing spinner values when switching case tabs

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#34]
The district, community and facility values from the "case data" tab are missing after the following has happened:

- Open the case
- Switch to the symptoms tab
- Wait for a few seconds
- Switch to the patient tab
- Switch to the case data tab

The (likely) reason is that the onResume() method of the case data tab is already called when the patient tab is opened which results in the selectedValue variable for the region spinner to return null (which, in turn, means that no district will be selected).

**Comment by MateStrysewskeSym** [comment]
Possibly fixed by adding an offscreen page limit, needs review.

**Comment by StefanSzczesny** [comment]
see #54 for activity status
