### ISSUE TITLE
Logic to calculate "follow-up until" for a contact

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#35]
This is basic implementation of the logic that is not complete

- [x] Add status "no follow-up"
- [x] Show follow-up until and status in contact form
- [x] Duration: Ebola, Cholera 21 days, Lassa 6 days
- [x] Leave empty and set follow-up status to "No follow-up" for other diseases
- [x] Reference for calculation is the reporting date (since this is always later than the last contact date and we can't be sure the last contact date is correct)

**Comment by MartinWahnschaffeSymeda** [comment]
Done. In the future we should probably change the way the follow-up status is used.

**Comment by StefanSzczesny** [comment]
- [ ] fix code comments
- [ ] constrain date of last contact before report date

**Comment by MartinWahnschaffeSymeda** [comment]
All done now
