### ISSUE TITLE
Update Vaadin Theme with new Design

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#356]
### Controls
- [x] button
- [x] text field/area
- [x] checkbox
- [x] combo box
- [x] replace native selects with vaadin combo boxes
- [x] radio select
- [x] read-only controls -> labels
- [x] grid
- [x] popup

### Layouts
- [x] SORMAS Logo
- [x] Entry & selection colors
- [x] Show menu selection in sub views
- [x] use bootstrap 3 grid
- [x] clean up old css styles
- [x] commit-discard layout
- [x] view header
- [x] sub menu
- [x] header styles

**Comment by MartinWahnschaffeSymeda** [comment]
Done.
For further todos see #361, #362, #363

**Comment by MartinWahnschaffeSymeda** [comment]
Fixes:

- [ ] not sure -> unknown
- [ ] switch save & discard
- [ ] table styles + wrap text
- [ ] background white
- [ ] first symptom only visible when there is a symptom
- [ ] Case contacts and other sub-grids: remove sub header
- [ ] Make sure to add margin to all sub components
- [ ] Contact classification: Make it short in tables
- [ ] Case contacts filter have no caption. And whats the second filter?
- [ ] type of contact -> vertical
- [ ] contact form -> more width
- [ ] cancel, lost buttons -> remove caption space
- [ ] follow-up status should have blue background
- [ ] user popup

**Comment by MateStrysewskeSym** [comment]
- [ ] remove white button border on Dashboard
- [ ] remove white outline of highcharts labels
