### ISSUE TITLE
Create entity creator for test classes

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#359]

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Introduce FacadeBeanTest that provides all the needed facades and services to tests. Extends BaseBeanTest
- [ ] TestDataCreator should not be a BeanTest class. Instead use FacadeBeanTest in constructor
- [ ] create methods should only build, not save (also rename)
