### ISSUE TITLE
Add disease "monkeypox" to SORMAS [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#366]
- [x] The relevant fields need to be defined in the data dictionary https://docs.google.com/spreadsheets/d/1BA_RjM-ZhxFrzpAJdv0UVGhicHXNP6JnPBA-xzdrQKs/edit#gid=1141530889
- [x] contact investigation and follow up is needed (21 days)
- [x] add sample material "crust"
- [x] add test type "antigen detection test"

### Additional fields.

Case person - medical data

- [x] "Is a smallpox vaccination scar present" - YNU

Case symptoms

- [x] "Name of the village (and country) where the patient got ill" - text. Required when a symptom is checked
- [x] "Does the patient have a cutaneous eruption?"  - YNU
- [x] "If yes, date of onset for the rash"  - date
- [x] Fever?: "If yes, date of onset for the fever"
- [x] Add "Lesions" symptom that enables Lesions that itch as well as the specifications below
- [x] "Are the lesions in the same state of development on the body?" -YNU
     "Are all of the lesions the same size?" - YNU
     "Are the lesions deep and profound?" - YNU
- [x] "Localisation of the lesions": Face, Legs, Soles of the feet, Palms of the hands, Thorax, Arms, Genitals, All over the body - multiselect
- [x] "Do the lesions resembe (for each photo) - YNU 
![grafik](https://user-images.githubusercontent.com/23217632/31876931-cb6176a0-b7d4-11e7-82ed-3cc8b3ad1317.png)
![grafik](https://user-images.githubusercontent.com/23217632/31876933-cf0f6eba-b7d4-11e7-9695-622a666d3ef0.png)
![grafik](https://user-images.githubusercontent.com/23217632/31876935-d206e5b2-b7d4-11e7-840f-367727095cf3.png)
![grafik](https://user-images.githubusercontent.com/23217632/31877584-54112d36-b7d7-11e7-93b0-d90eea4a4ffd.png)
- [x] Symptoms: "Lymphadenopathy, inguinal", "Lymphadenopathy, axillary", "Lymphadenopathy, cervical", "Chills or sweats", "Lesions that itch", "Is the patient bedridden"

Epi data:

- [x] Add a general information above travel, burial, etc. "Please indicate if any of the following is relevant for the patient during the incubation period or illness."
- [x] Instead of "What kind of animal" (form) use rodents, primates, other + detail
- [x] "Date of last exposure" - date
- [x] "Condition of animal last exposed to": Dead/alive/processed/unknown
- [x] "Place of last exposure" text field (-> add to Other disease, don't show all other fields of this kind)

### Questions @hzi-braunschweig 

- Our current system of animal contact documentation is a bit different from the monkeypox case investigation form. I think we should implement it the way it's suggested in the form, but I'm not sure about this. What do you think? -> see above
- Contact proximity -> aerosol

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Algorithm for responding to monkeypox
![image](https://user-images.githubusercontent.com/19344651/31885116-b650f770-b7ef-11e7-9706-bd8d00de97e9.png)

**Comment by hzi-braunschweig** [comment]
Monkeypox Case Definitions 
Suspected case of monkeypox: Any person presenting with a history of sudden onset of fever, followed by a vesiculopustular rash occurring mostly on the face, palms and soles of feet.
Confirmed Case: Any suspected case with laboratory confirmation (Positive IgM Antibody, PCR or Virus isolation). 
Contact: Any person who has no symptoms but who has been in physical contact with a suspected case or with body fluids of a case in the last three weeks (i.e. skin secretions, oral secretions, pre-mastication of food, urine, stools, vomiting, blood, sexual contact).
During suspected outbreaks, States are to intensify surveillance and actively engage in case search for early detection. All rumours should be investigated and recorded in a rumour log. A case investigation form (Refer to Annex A) must be completed for all suspected cases and cases should be line listed. 
The following are to be carried out for every detected suspected case:
1.	Clinical examination of the patient 
2.	Questioning of the patient about possible sources of infection and the presence of apparent diseases in the patient's community
3.	Completion of a case investigation for each patient
- The case investigation form must be completed for each patient who meets the case definition
- Clinical Photographs showing the lesions should be taken with permission from the patient
4.	Collection and transportation of samples as detailed in sample collection protocol as detailed below 
 

Monitoring Contacts of monkeypox patients
The contacts of animals or humans confirmed to have monkeypox or probable cases should be placed under symptom surveillance for 21 days after their last exposure. Symptoms of concern include fever, sore throat, cough, or skin rash. Contacts should monitor and record their temperature twice daily. In addition, they should maintain daily contact with the designated surveillance officer or health worker. 
Contacts who develop symptoms of monkeypox (i.e., fever, muscle aches, headache) should be placed under rash surveillance for 7 days following fever onset. If no rash develops, contacts should continue to monitor for symptoms for an additional 14 days (21 days total symptom surveillance). If symptoms return or if rash develops the LGA/State team should be notified immediately.  
Healthcare workers who have unprotected exposures (i.e., not wearing PPE) to patients with suspected monkeypox need not be excluded from duty, but should undergo active surveillance for symptoms, including measurement of temperature at least twice daily for 21 days following the exposure
Information should be documented in the contact monitoring form.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
![image](https://user-images.githubusercontent.com/19344651/31885287-4f1640e6-b7f0-11e7-8449-933a8d11807e.png)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
**Monkey pox transmission contact types**
Transmission of monkeypox virus occurs when a person comes into contact with the virus from an animal, human, or materials contaminated with the virus. The virus enters the body through broken skin (even if not visible), respiratory tract, or the mucous membranes (eyes, nose, or mouth). Animal-to-human transmission may occur by bite or scratch, bush meat preparation, direct contact with body fluids or lesion material, or indirect contact with lesion material, such as through contaminated bedding. Human-to-human transmission is thought to occur primarily through large respiratory droplets. Respiratory droplets generally cannot travel more than a few feet, so prolonged face-to-face contact is required. Other human-to-human methods of transmission include direct contact with body fluids or lesion material, and indirect contact with lesion material, such as through contaminated clothing or linens.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 

Please separate aerosols and droplets as different contact proximity types.
