### ISSUE TITLE
Rename "Alert" to "Event"

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#367]

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig @dta16 The WHO use "Event" themselves. We should probably talk about this again.

**Comment by dta16** [comment]
We agreed changing from alerts to events.

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 "We" means Gérard and you? Just asking to be sure about this one...
