### ISSUE TITLE
Add additional smallpox vaccination questions for monkeypox

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#375]
- [x] add question "Have you received a small pox vaccination in the past?"
- [x] add date field "Date of vaccination"
- [x] add picture to the scar question: ![smallpox-vaccination-scar](https://user-images.githubusercontent.com/23217632/32328964-dff9c112-bfdb-11e7-93fc-a696c2d10e64.jpg)

**Comment by bernardsilenou** [comment]
This has not yet been implemented in the app but it is in the dictionary. We also need to add the source of information if the answer to the question "smallpoxVaccinationReceived" is yes
