### ISSUE TITLE
URGENT: ISSUES FROM THE MONKEY POX OUTBREAK

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#380]
@MartinWahnschaffeSymeda @MateStrysewskeSym
To be implemented in next version urgently...
- Expand search functionalities (by epid number) #384
- National user to be able to create cases for outbreak mode #385
- National user to be able to filter by State and LGA #386
- National user instance should have in his table the column for state and LGA. -> discuss
- Add Missing (99) to no responses in drop down for required fields that are empty #397 
- Expand Epi curve as Map expand functionality is #387 
- Is it true that we can only display cases for which we have an onset date or for which we have a classification ? If this is the case it needs to be changed urgently. Especially in the dashboard one must be able to see cases that have not been classified as suspect , probable or confirmed yet under the label „not yet classified“. #387
- Also onset date are often not known. So deflation should be to plot the lists and epi curved by date or week of notification. (We had talked about it before) -> we have to consistently use one date. For now this will be the date of report #387
- Let health facility be picked without selection of wards #382 
-  On the map, show filter options between Geo-coordinates for health facilities and for case home address. #388
-  Add show district on map (only region option exists) #342 
- Tests results- IGM checks for immediate infection and PCR looks for antibodies -> unclear
- add "Source tracing" to the system to the contact tracing. Where is the source coming from? #389
- Match or pick person not working. #390
- error in putting source case as contact and inability to delete it. setting to not a contact and recreating as a case does not work. -> see #383 
- Investigation pending remains after task completed for retrospective data -> maybe not properly synchronized? Works for us
- Alert section, surveillance officer does not show -> probably LGA is not selected or the LGA has no officer
- Filter by Health facility on list directories #384 
- What happens to geo coordinate when case is created at home or other health facililty? -> unclear
- admin with national user privilege cannot save any data at the state level -> unclear
- Allow supervisors the ability to change investigation status to investigation done -> we have explicitely changed this. Supervisor can do this by assigning the investigation task to himself and setting it to done.
- SORMAS crashes when you move a case that has no health facililty #381 
- User should not be able to save a case without assigning a health facility(home or place or other health facility) -> works for us
- Supervisors should be able to edit health facility details #232
- Change NIRL to NCDC Laboraroty (NRL) Gaduwa -> can easily be done in the database. Make sure to create a regular backup

---

Fix asap:
- Allow admins to delete entities #383
- Allow users to select a facility without selecting a ward first (automatically select the right ward in this case or let the system handle the case where no ward is selected) #382 
- Fix Android app crashing when "Home or other place" is selected as a health facility and trying to move the case (Maté: I can't reproduce this bug) #381

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Which exact fields should have the "missing/unknow" entry? We need a precise list. What about the symptoms onset field - should there be a checkbox next to it that has to be checked when no onset is known?

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Hi Daniel, we went through all the points and created individual issues. These are referenced above. Some of the points are marked as unclear. Please elaborate on those.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
Some required fields are left blank on the paper forms and hence the officers may not have the information to put in at the time and may be tempted to put a wrong date just to continue. Please just add to all required field a "no response" option in the dropdown or "missing" as an option to all required fields to give the officers flexibility to enter missing when the data field is blank

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 @Krisistis As far as I can see, we are supposed to add a new sample test type to the system:

> Tests results- IGM checks for immediate infection and PCR looks for antibodies

What should the name of this test be?

**Comment by hzi-braunschweig** [comment]
IGM Test and PCR AntiBodies

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda

**Comment by MartinWahnschaffeSymeda** [comment]
See #419.

Closing this, since all issues are in separate tickets now.
