### ISSUE TITLE
Fix Android app crashing when "Home or other place" is selected as a health facility and trying to move the case

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#381]

**Comment by MateStrysewskeSym** [comment]
@dta16 I need a very specific explanation on how this happened. I see the app crashes in Google Analytics and I know where exactly in the code the error happens, but I still can't reproduce it. Please give me a step-by-step instruction on what I need to do in order to provoke this error.

**Comment by MartinWahnschaffeSymeda** [comment]
Was probably related to the database update.
There are some cases wwhere facility is still msising

**Comment by hzi-braunschweig** [comment]
![image](https://user-images.githubusercontent.com/19344651/32552499-712171f0-c494-11e7-8a15-27e48c78ad6e.png)

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 I have set the health facility for the two cases that didn't have one in the database. Moving should be working now. I'm still wondering how this could happen.
