### ISSUE TITLE
Search case and contacts by EPID number and contact first name and last name respectively....

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#384]
- [x] Search case by EPID number
- [x] Filter by Health facility on list directories. Disabled until LGA is selected. Add according description
- [x] add filter for present condition to case directory

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
Search case by the following entities:
-[ ] Epid Number
-[ ] First Name
-[ ] Last Name
-[ ] Date of Report

Search contact by the following entities:
-[ ] Contact classification
-[ ] Contact person
-[ ] Source case
-[ ] First Name
-[ ] Last Name
