### ISSUE TITLE
Allow National user to filter cases, contacts and samples by State and LGA

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#386]
@dta16 Besides cases, contacts and events, is there anything else that needs to be filter by state and/or LGA?

**Comment by dta16** [comment]
Hi martin,
Yes, Reports, Samples

regards

On Tue, Nov 7, 2017 at 4:17 PM, Martin Wahnschaffe <notifications@github.com

**Comment by MartinWahnschaffeSymeda** [comment]
Cases, Contacts, Samples done.

Not implemented for events, because it doesn't seem to be needed there now.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Fix: CaseIndexDto user filter only returns cases with a surveillance officer
