### ISSUE TITLE
Use report date instead of symptoms onset for epi curve and other dashboard data

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#387]
- [x] Use report date instead of symptoms onset for epi curve and other dashboard data
- [x] show not yet classified cases in epi curve
- [x] show not yet classified cases in map (grey icons)
- [x] remove map specific filters
- [x] add expand button to epicurve
- [x] use DashboardCase object for epicurve and map

@dta16 To answer your question from #380 : yes, it is true that we can only display cases in the dashboard that have an onset date. This was implemented based on what we discussed. See https://github.com/hzi-braunschweig/SORMAS-Open/issues/78#issuecomment-270462744

We will change this now based on the changed requirements.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
- [ ] Please for the epicurve, we need to be a bit flexible. let us have a filter to filter by report date, alive/dead, date of symptoms and confirmed/probable/suspected/not yet classified cases
- [ ] The dashboard data should also be a bit flexible to handle filters and search by date of reports, date of onsets, by confirmed/probable/suspected/not yet classified cases, by LGA, By State, and other elements, also search by demographics for male, female, etc

**Comment by MartinWahnschaffeSymeda** [comment]
As discussed: 
- [ ] show by date of report now
- [ ] later add option to display by date of onset + info on the number of cases
