### ISSUE TITLE
On the map, show filter options between geo-coordinates for health facilities and for case home address.

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#388]
@dta16 
What about cases that don't have gps for the home address? Should they not be displayed at all or use the report geo coordinates?

**Comment by dta16** [comment]
Report Geocoordinates is a good alternative.

Thanks

On Tue, Nov 7, 2017 at 4:31 PM, Martin Wahnschaffe <notifications@github.com

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] rename layer options to "... by home address" and "... by health facility" and add description for fallback to report GPS
