### ISSUE TITLE
Task "investigate case"

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#39]
- [x] Generate task for case with investigation status pending
- [x] Assign to officer or supervisor
- [x] Officer can do task or set it to "not executable"
- [x] Investigation status is updated accordingly (pending, canceled, done)
- [x] Creating a new "investigate case" task will update the case investigation status
- [x] Nobody can change the investigation status manually
- [x] Wrap logic in own service
- [x] Process diagram to visualize what is happening

**Comment by MartinWahnschaffeSymeda** [comment]
Diagram is created in libre office draw: https://github.com/hzi-braunschweig/SORMAS-Open/blob/development/sormas-base/doc/case%20surveillance/case%20investigation%20status.odg
