### ISSUE TITLE
Replace required fields with "should" fields (like EPID-number)

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#397]
- [x] collect all fields
- [ ] change in app ui
- [ ] change in backend database (if needed)
- [ ] change in web ui

**Comment by MateStrysewskeSym** [comment]
Fields that have to be turned into "should" fields:

### Previous Hospitalization
admissionDate, dischargeDate

### Symptoms
onsetDate, onsetSymptom

### EpiData
Burial: burialStart, burialEnd; Social event: eventDate; Travel: travelStart, travelEnd; 

### Contact
contactProximity, relationToCase

### Alert
srcFirstName, srcLastName, srcTelNo, typeOfPlace, dateOfAlert?

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 
Here the list of all required fields to be changed. We suggest to keep the existing required fields for sample and sample test.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Please also do not let responsible officer be a required field. it is causing alot of problems for the supervisors and rumor officer. Can you not make it a required field?


Thanks

**Comment by hzi-braunschweig** [comment]
![image](https://user-images.githubusercontent.com/19344651/32656069-a0e033a4-c610-11e7-98ae-231bc6187b17.png)

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig It's already in the list, we'll remove that requirement.
