### ISSUE TITLE
Manage buttons in status bar of tab-based activities

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#4]
Add listener to update the visibilty of chosen buttons in the statusbar in the cases edit activity.

    ​https://developer.android.com/guide/topics/ui/menus.html#ChangingTheMenu
    ​https://developer.android.com/guide/topics/ui/menus.html#groups

**Comment by StefanSzczesny** [comment]
setOnPageChangeListerener() for PagerAdapter to trigger the invalidateOptionsMenu()
