### ISSUE TITLE
Split CaseStatus to CaseClassification and InvestigationStatus

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#40]
- [x] CaseClassification: Possible case, Suspect, Probable, Confirmed, Not a Case
- [x] InvestigationStatus: investigation pending, investigation done, discarded
- [x] Update data dictionary

**Comment by MartinWahnschaffeSymeda** [comment]
This is pushed now.
I have updated the filters in the cases list of app and ui to the investigation status (pending, done, discarded).
In addition the app's database is now inititalized (makes sure tables exist) before everything else.
