### ISSUE TITLE
Additional monkeypox fields (symptoms) [0.5]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#401]
QUESTIONS TO ADD TO SORMAS
EXPOSURES:
•	During the three weeks preceding the onset of symptoms, did the patient have contact with one or more persons who had with similarnsymptons?
Yes                   No                   Do not know
•	If yes, respond to the following questions concerning these additional ill people (indicate all of the ill people). There is additional space for multiple contact at the end of this form.
•	Last name _______________________ First name __________________________
•	Relationship with the patient ___________________________________________
•	First date of contact with the ill person ___/ ___/ ____

•	Interaction with this person (choose all that apply)
- [ ] Family contact / Live together
- [ ] Prepared food together
- [ ] Shared a bed / slept together
- [ ] Took care of this sick person
- [ ] Friend at school or for play
- [ ] Met at the market
- [ ] Hunted together
- [ ] Friend / social acquaintance
- [ ] Were at the church, assisted at a religious service together
- [ ] Other __________________________________________________

•	Other information about the contact
_______________________________________________________________________
_______________________________________________________________________

Under symptoms add
- [x] Rename lesions to rash
- [x] Remove cutaneous eruption as its the same with lesions.
- [x] Add date of rash onset

**Comment by MartinWahnschaffeSymeda** [comment]
See #389
