### ISSUE TITLE
Newly created sormas users assigned to specific states

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#409]
@MartinWahnschaffeSymeda 
All newly created sormas users assigned to Lagos state for instance, do not see previous cases assigned to the same state or LGAs except cases created by them (even the supervisors), This should not be so, It was not like this before the last version.

**Comment by hzi-braunschweig** [comment]
it happens for all states users newly created and old users as well. they cant see previously entered data by them

**Comment by MateStrysewskeSym** [comment]
Probably fixed in commit https://github.com/hzi-braunschweig/SORMAS-Open/commit/8ae031dd592d1c1bd40469fed866f972169f6007
