### ISSUE TITLE
Update symptoms from Datadictonary

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#41]
- [x] define what to do

[api + backend]
- [x] use sormas-api/tools/Fields.xlsx to update SymptomsDto from DataDictonary (copy into "Fields" worksheet)
- [x] update .properties (also from Fields.xlsx)
- [x] use DtoAdoCodeGenerator.generateCopyJava() for SymptomsFacadeEjb.toDto and .fromDto
- [x] add missing members to Symptoms
- [x] use DtoAdoCodeGenerator.generateNotMatchingMembersList to find no longer needed members in Symptoms
- [x] sormas_schema SQL
- [x] use DtoAdoCoderGenerator.generatePropertyConstantsJava

[ui]
- [x] update SymptomsForm; order symptoms as in DataDictionary
- [x] date of onset only required when any symptom
- [x] update SymptomsForm layout

[app]
- [x] update Symptoms entity
- [x] update layout
- [x] date of onset only required when any symptom. should probably be asked last in app (but displayed first in webui)

**Comment by MateStrysewskeSym** [comment]
According to Martin, "SymptomOnset" has to be renamed to "OnsetDate" and "FirstSymptom" to "OnsetSymptom" in the data dictionary; I currently don't have write permissions.

**Comment by MateStrysewskeSym** [comment]
Discuss whether the "symptomatic" field is needed

**Comment by StefanSzczesny** [comment]
- [ ] remove requirement for "other" text field and bind it to the respective radio button
- [ ] make "other" text fields required when radio button is set to "Yes"

**Comment by MartinWahnschaffeSymeda** [comment]
DataDictionary updated
