### ISSUE TITLE
Enable Batch/Bulk Operations [5]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#411]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
Allow admin to perform batch operations when cleaning and sorting the data. For instance allow multiselection or all rows to perform one type of operation (e.g change state from unconfirmed contacts to confirmed contacts)

**Comment by MateStrysewskeSym** [comment]
- [ ] Add checkboxes to all directories (also sub-directories, e.g. samples in a single case)
- [ ] Add a dropdown button containing two elements: "Delete" and "Change..."
- [ ] Implement delete bulk operation for all directories
- [ ] Add "Cancel follow-up" and "Lost to follow-up" to the dropdown for contacts
- [ ] Open a popup window when clicking on "Change..." that differs depending on the directory, containing elements to change the following fields for all selected entities:

Cases:

- [ ] Case classification
- [ ] Investigation status
- [ ] Outcome
- [ ] Surveillance officer

Contacts:

- [ ] Contact classification
- [ ] Responsible contact officer

Events:

- [ ] Event type
- [ ] Event status

**Comment by MateStrysewskeSym** [comment]
- [ ] extend follow-up comment: "Canceled by ... using bulk action"
