### ISSUE TITLE
Health facility geo coordinates on the map does not work

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#415]
![image](https://user-images.githubusercontent.com/19344651/32981652-a9a7158e-cc78-11e7-8591-6717afe9aa94.png)

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig Could you please provide a bit more information? Which user roles had the active user? What does the error say that pops up when you hover over the red exclamation mark below the "Show facilities" check box?

**Comment by hzi-braunschweig** [comment]
@MateStrysewskeSym  another error is with the incidence and region color coded. Rivers state has a bug, it is reading its incidence and number of cases wrongly. Even after region checkbox is inactive, rivers state still shows a color. Please convert incidence colors on maps and case counts to quartiles
![image](https://user-images.githubusercontent.com/19344651/33034543-70fd839c-ce28-11e7-9ddd-d3435423e534.png)

**Comment by MateStrysewskeSym** [comment]
@dta16 Can you tell us if the issue with the health facilities not appearing on the map still exists in the new version?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
It is still not working. Same error. We still have health facility field showing null. and no lab dropdown

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig That's not what I wanted to know. I asked for an update on the facility markers not showing on the case status map issue. Is this still not working?

**Comment by hzi-braunschweig** [comment]
Mate,

It is still not working!


Tom-Aba Daniel (MPH B.Sc)
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de
Mobile: +495316181-3124
________________________________

**Comment by MartinWahnschaffeSymeda** [comment]
Found a case without health facility (caused by #427 ). We manually set it to "other". The map works now.
