### ISSUE TITLE
Add new test types "IGM Test" and "PCR AntiBodies"

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#419]
Existing test types are:

- PCR
- RT-PCR
- ELISA
- Culture
- Microscopy
- Virus isolation
- Rapid test
- Antigen detection test
- Serum antibody (Ab) titer
- Other

New tests:

- [ ] IGM Test
- [ ] PCR AntiBodies

@dta16 Please have a quick look and to confirm this is correct

**Comment by hzi-braunschweig** [comment]
This is complete. If you add the new test, then it would be redundant. Id suggest we do not add the new test labels to the list as they already exist in the list.

Thanks

Tom-Aba Daniel (MPH B.Sc)
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de
Mobile: +495316181-3124
________________________________________

**Comment by MartinWahnschaffeSymeda** [comment]
Ok, if I got you right this is not needed and can be closed.
