### ISSUE TITLE
Report Confirmation by Informants failed!

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#425]
![img-20171125-wa0002](https://user-images.githubusercontent.com/19344651/33229553-3209c4be-d1d1-11e7-85dc-2c6a7dbdd6b5.jpg)
@MartinWahnschaffeSymeda See picture 
On user login change, the report confirmation works. No synchronization errors seen

**Comment by MartinWahnschaffeSymeda** [comment]
Might be related to the health facilities missing

**Comment by MartinWahnschaffeSymeda** [comment]
Stacktrace:


> . | RuntimeException  - Root cause: android.database.sqlite.SQLiteConstraintException: NOT  NULL constraint failed: weeklyreport.healthFacility_id (Sqlite code  1299), (OS error - 2:No such file or directory) - Stack trace:  de.symeda.sormas.app.backend.common.AbstractAdoDao:callBatchTasks:1046  ->  de.symeda.sormas.app.backend.common.AdoDtoHelper:handlePullResponse:95  -> de.symeda.sormas.app.backend.common.AdoDtoHelper:pullMissing:188  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync:pullMissingAndDeleteInvalid:226  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:71  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:103  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:doInBackground:267  -> android.os.AsyncTask$2:call:316 ->  java.util.concurrent.FutureTask:run:237 ->  android.os.AsyncTask$SerialExecutor$1:run:255 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:776 - Root cause stack trace:  android.database.sqlite.SQLiteConnection:nativeExecuteForLastInsertedRowId:-2  ->  android.database.sqlite.SQLiteConnection:executeForLastInsertedRowId:818  ->  android.database.sqlite.SQLiteSession:executeForLastInsertedRowId:803  -> android.database.sqlite.SQLiteStatement:executeInsert:86 ->  com.j256.ormlite.android.AndroidDatabaseConnection:insert:157 ->  com.j256.ormlite.stmt.mapped.MappedCreate:insert:91 ->  com.j256.ormlite.stmt.StatementExecutor:create:450 ->  com.j256.ormlite.dao.BaseDaoImpl:create:310 ->  de.symeda.sormas.app.backend.common.AbstractAdoDao:create:1000 ->  de.symeda.sormas.app.backend.common.AbstractAdoDao:mergeOrCreate:614  -> de.symeda.sormas.app.backend.common.AdoDtoHelper$1:call:100 ->  de.symeda.sormas.app.backend.common.AdoDtoHelper$1:call:95 ->  com.j256.ormlite.misc.TransactionManager:callInTransaction:168 ->  com.j256.ormlite.stmt.StatementExecutor:callBatchTasks:553 ->  com.j256.ormlite.dao.BaseDaoImpl:callBatchTasks:633 ->  de.symeda.sormas.app.backend.common.AbstractAdoDao:callBatchTasks:1044  ->  de.symeda.sormas.app.backend.common.AdoDtoHelper:handlePullResponse:95  -> de.symeda.sormas.app.backend.common.AdoDtoHelper:pullMissing:188  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync:pullMissingAndDeleteInvalid:226  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:71  -> de.symeda.sormas.app.rest.SynchronizeDataAsync:doInBackground:103  ->  de.symeda.sormas.app.rest.SynchronizeDataAsync$2:doInBackground:267  -> android.os.AsyncTask$2:call:316 ->  java.util.concurrent.FutureTask:run:237 ->  android.os.AsyncTask$SerialExecutor$1:run:255 ->  java.util.concurrent.ThreadPoolExecutor:runWorker:1133 ->  java.util.concurrent.ThreadPoolExecutor$Worker:run:607 ->  java.lang.Thread:run:776
> -- | --

-> it really is related to the health facility problem. See #427

**Comment by MartinWahnschaffeSymeda** [comment]
Solved by #427
