### ISSUE TITLE
Follow up Visits: Save logic error

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#426]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
When a visit is being conducted and the user starts with data entry: Available, or unavailable, date of visit etc and wants to go to symptoms, all users are trained to click save to automatically go to the symptoms page and when they click on save, it goes to symptoms but does not allow the user scroll up to enter any information. It has all fields with error remarks (state cannot be empty). But if save is not clicked before going to symptoms, but clicked after both tabs have been filled out, everything goes well

**Comment by MateStrysewskeSym** [comment]
@hzi-braunschweig We've adjusted the order in which the symptoms are validated, which means that users will now be taken to the first symptom that has not been specified when they set the visit to available and cooperative and click on save.
