### ISSUE TITLE
Contact Officer not seeing contacts to follow up

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#428]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
In Kiru LGA Kano state, contact officer does not see contacts to follow up. 
Health facility for case was blank- possible cause of error.

When case is moved to another LGA, another contact officer can see the contacts. 
![img-20171125-wa0030](https://user-images.githubusercontent.com/19344651/33231775-40cfe904-d1fb-11e7-809d-cf6bbb039a12.jpg)

**Comment by MartinWahnschaffeSymeda** [comment]
Solved by #427
