### ISSUE TITLE
Make duplicate search more fault-tolerant [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#432]
Apply a search for similar names to make it more likely to find existing persons and their cases.

- [x] Define a pattern (similarty score): first name and last name. District level in app, region level in web (country level might become too slow and **should be done in a seperate merge view for national users**).
- [x] Apply the pattern to the search for similar persons when creating a new case. Will likely be necessary to load all names and apply to pattern to them. Would be good to narrow this down in the querry
- [x] Add persons that match the pattern to the list of similar persons to allow the user to choose one of them
- [x] produce realistic test data to experiment with this
- [x] Adjust threshold accordingly

Algorithm:

- [x] Use Levenshtein Distance
- [x] Split first and last name (whitespace, _, -), create array containing all parts (for both person names)
- [x] Use smaller array as base
- [x] Create array with similarity results
- [x] For every entry, compare the entry with all entries of the other array and store the highest value in similarity result array
- [x] Set entry in comparison array that reached this value to null
- [x] Calculate average and use this as threshold

**Comment by MateStrysewskeSym** [comment]
- [ ] write native query that only returns objects containing first and last name and uuid initially (for the list of existing persons), call it PersonNameDto in Vaadin app

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make first and last name required in select or create person popup
- [ ] remove empty elements from string arrays before calculating the distances
- [ ] remove new queryRaw method
- [ ] use PersonNameDto in app

**Comment by MateStrysewskeSym** [comment]
- [ ] make sure that a maximum height for the grid is set
