### ISSUE TITLE
Laboratory is not transferred to phone

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#434]
- [x] NIMR laboratory is not transferred to the mobile app ("Abuja" is set as region in .csv file although it's not a region in the system -> change)
- [x] Region of laboratories LUTH, IRLC, ISTH, NIRL ist missing, which lead to duplicates -> set region and write SQL to merge duplicates
- [x] enable deletion of invalid infrastructure in sync mechanism

**Comment by MateStrysewskeSym** [comment]
Looks like the first point was fixed in #433

**Comment by MartinWahnschaffeSymeda** [comment]
Update NIMR in existing databases:

> UPDATE public.facility
>  SET changedate=now(), region_id=(SELECT id FROM region WHERE region.name='FCT')
>  WHERE name='NIMR - Nigerian Institute for Medical Research';
