### ISSUE TITLE
Reception date for case [0.5]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#438]
@MartinWahnschaffeSymeda @MateStrysewskeSym 

- [x] ~~Date of investigation~~ -> already there
- [x] Date of reception

**Comment by MartinWahnschaffeSymeda** [comment]
Actually we already have "da of investigation" in the database. It is automatically set for a case whenever the investigation status is set to done.

@dta16 
What does "date of reception" mean? Who is receiving what?

**Comment by MartinWahnschaffeSymeda** [comment]
Date of reception is needed so people on national level can enter when the paper form was received.

- [ ] Add a description "Date the case information was received at the state or national level."

**Comment by MateStrysewskeSym** [comment]
- [ ] create and re-use filter in EpiCurveComponent
