### ISSUE TITLE
"Cause of death" for person [3]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#439]
@MartinWahnschaffeSymeda @MateStrysewskeSym 

Additional option for death due other causes. High alert. 

- Dead due to specific disease (e.g monkeypox
- Dead due to other causes

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 

I'd suggest to add a field "Cause of death" that comes with the options: "Infectious disease", "Other disease", "Other cause"
When "Epidemic disease" is selected a field that allows the selection of the disease and is pre-filled with the case disease will be shown. 
When "other disease" or "other cause" is selected a text field is shown.

This need discussion.

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 What does "high alert" mean?

**Comment by MartinWahnschaffeSymeda** [comment]
Meeting 15.12.17: "high alert" was about this issues being very important.

Implement as suggested. In addtion:

- [ ] present condition: alive by default and soft-required
- [ ] gender soft required
