### ISSUE TITLE
GPS tag for done tasks (e.g. for done visits)

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#44]

**Comment by hzi-braunschweig** [comment]
@StefanSzczesny This is important because the GPS tags will be the ones that would also be shown on the web dashboard for contacts map showing clustering of contacts by cases and by visits done. @gstephan30 @stoikkanen

**Comment by stoikkanen** [comment]
based on today's discussion with Gérard: The GPS tags can be moved down on the priorities

**Comment by MartinWahnschaffeSymeda** [comment]
See #86
