### ISSUE TITLE
Add "Other laboratory" option for sample and sample test

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#440]
- [x] change NIRL to National reference Lab Gaduwa
- [x] Add other Laboratory for labs that do not exist within SORMAS

@MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Add "other laboratory" as general option for lab selection fields (sample and sample test)
- [ ] The "other laboratory" option should open a text-field - the same way it is done for the health facility of a case.
- [ ] previous hospitalization needs a facility name field as well

@dta16 Is NRLG a different name for the same laboratory or another laboratory?

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] NIRL has been renamed to NRLG -> do the same in the github data

**Comment by MateStrysewskeSym** [comment]
Has to wait until the new design is rolled out in the field

**Comment by MartinWahnschaffeSymeda** [comment]
Repriorized

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Probably makes sense to do #627 at the same time.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make sure that laboratory details field is only shown when other laboratory is selected in edit form
- [ ] rename "includeOtherFacility" to "includeOtherLaboratory"
