### ISSUE TITLE
Urgent- Print option and Situation report generation in SORMAS

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#441]
High priority! @MartinWahnschaffeSymeda @MateStrysewskeSym 

We need to be able to export data into csv, pdf and excel and most important generate sitreps from the database automatically

**Comment by MartinWahnschaffeSymeda** [comment]
This is a duplicate of #391 and as far as I understand the generation of a situation report is another separate feature.

The current version will come with a new basic statistics section: #396 

I'd suggest to discuss this in depth, when we meet.
