### ISSUE TITLE
Allow app user to have multiple roles [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#444]
1. allow app user to have multiple roles

- [ ] ~~add UserRole entity representation~~
- [x] add user roles to user entity. Persist as JSON string
- [x] adjust depending code
- [x] update local database

2. restrict the combination of user roles: 

- [x] informants can not have another role at the same time.
- [x] officers can have the different officer roles (surveillance, case, contact)
- [x] supervisors, rumor manager and lab user can be combined with each other
- [x] lab user can be combined with national user
- [x] admin can be combined with any of the above

See also #278

**Comment by MartinWahnschaffeSymeda** [comment]
Solved the android part by persisting the enum set as json string.

**Comment by MateStrysewskeSym** [comment]
Seems like app.backend.User.toString() throws a NullPointerException.

**Comment by MartinWahnschaffeSymeda** [comment]
Could not reproduce the null pointer. Other things are fixed.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] unit test the consistency of getCombinableUserRoles
