### ISSUE TITLE
Check logback config on servers and development environment

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#448]

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] replace my e-mail adress with default sormas support e-mail adress
- [ ] add description on what to add to dev environment logback.xml

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] update logback config on sormas.symeda.de
- [ ] update logback config on sormas.org.ng
