### ISSUE TITLE
Investigation status and date editable [0.5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#453]
Web users that have the CASE_INVESTIGATE right should be able to directly edit investigation status and date so existing "paper" cases can be added retrospectively.

- [x] web users can edit investigation status
- [x] web users can edit investigation date (field exists in domain, but is currently not in UI)

Changelog:
- added reference to CASE_INVESTIGATE user right (because certain user roles, e.g. lab users, should not be able to edit the investigation status at all)

**Comment by MateStrysewskeSym** [comment]
- [ ] fix bug that resets the investigation status
- [ ] make sure that investigated date is automatically set if empty
