### ISSUE TITLE
Line listing for CSM [5]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#459]
line listing functionality 

S/N | Epid Number | State | LGA | Ward | Settlement | Health facility | Name | Sex | Date of Birth   or age( Age in year ( e.g 4y) Age in Months if <12 months ( e.g 9m | Date of onset   disease | Week of onset of   disease | Date seen at   Health Facility | Date of   Notification | No. of valid   Vaccine doses (0,1,2,99) | CSF taken Yes/No | Results Pos/Neg | Serotype | Type of test | Outcome     1=Died      2=Alive    99=Unknown | Comments | Fever (Yes/No) | Temperature (oC) | Source of   temperature | Stiff neck | Bulging   fontanelle | Altered level of   consciousness | Anorexia/loss of   appetite | Confused/disoriented | Convulsions/Seizures | Diarrhea | Fitiguw/General   weakenss | Headache | Joint   pain/Arthritis | Muscle pain | Nausea | Pain behind eyes | Shock(Systolic   bp< 90) | Skin Rash | Vomiting | Others (List)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Please add some more details on who needs this and how it is supposed to be used.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
For all users, when cases etc CSM, Cholera have been detected, once they have 5 cases or more to determine an outbreak, then the supervisor can switch from a surveillance mode with all fields as shown in SORMAS to an outbreak mode with limited fields as shown in the example above. So only those fields are active in the various tabs as shown in the CSM example. 

Task for us will be to get all outbreak mode forms for integration into the process. I will get the Nigeria team to do this. For now, what is urgent is the CSM outbreak currently ongoing. We need to use the above fields to start the process.

**Comment by MartinWahnschaffeSymeda** [comment]
Questions

- [ ] No. of valid Vaccine doses (0,1,2,99) | CSF taken Yes/No
- [ ] date seen at health facility?
- [ ] results pos/neg still means that a sample is added and then a result is added?!
- [ ] "Serotype"?
- [ ] symptom "Bulging fontanelle"
- [ ] symptom "Others" -> show all symptoms?
- [ ] what about epi data, contacts?

**Comment by MartinWahnschaffeSymeda** [comment]
I have more or less finished the UI implementation.
My feeling is that especially the hospitalization form does not make sense this way.
We likely need a way to combine multiple forms in a single outbreak view (e.g. hospitalization, symptoms and epi data).

@dta16 This will need a thorough review and discussion next Tuesday!

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] use an outbreak form that contains person, hospitalization, symptoms, epi data

@hzi-braunschweig 

- [ ] provide default outbreak field definitions for all the disease
