### ISSUE TITLE
Show number of entries for each directory [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#463]
A supervisor should see on each directory how many entries are currently visible given the active filters to get a better overview.

Suggestion: On the left side of the "link" filters.

- [x] display number of entries for each main view: tasks, cases, contacts, events, samples, users. Simply use the count from the vaadin container (see image below - use boostrap badge style https://getbootstrap.com/docs/4.0/components/badge/)
- [x] switch location of tag filters (e.g. investigation status) with dropdown/text filters
- [x] highlight active tag filter (e.g. "all") (see image below - use bootstrap nav style (https://getbootstrap.com/docs/4.0/components/navs/)

![grafik](https://user-images.githubusercontent.com/23217632/35225207-f29bc63a-ff87-11e7-8ae2-533cdee97670.png)

**Comment by MateStrysewskeSym** [comment]
- [ ] use LayoutUtil.span
