### ISSUE TITLE
Hide settings from the view of the mobile app users [1]

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#468]
@MartinWahnschaffeSymeda We found out that users in the field usually mistakenly log off after we configure the tablets and log them in. 
We expect them to only authenticate via the 4 pin authentication and not re-log in when they are in the field. 
So the solution is to bring to the global menu, the following items:
- [ ]  Synchronize
- [ ]  Re-synchronize Data
- [ ]  Change pin

The following need to be hidden:
- [ ]  LOGOUT
- [ ]  Server address URL

The admin should be able to use a pin to access the settings area to configure the server url when configuring the tablets and also to log out and log in or manage synchronization conflicts

We can discuss this if you need more explanation

**Comment by MartinWahnschaffeSymeda** [comment]
Instead of giving the admin a PIN, we show the current version. When the user taps it 5 times, the additional options (logout and server address) will be shown.
