### ISSUE TITLE
Outbreak mode per disease and district/region [3+3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#473]
A surveillance supervisor or national user can put SORMAS into outbreak mode for a specific disease and a set of districts or a region. This allows SORMAS to reduce the entered data to a limited field set that will be defined per disease.

- [x] Create moqups
- [x] Provide an internal API with the current outbreak status (OutbreakFacade)
- [x] Users can view the current outbreak status
- [x] Users can edit the current outbreak status

Tasks

- [x] create api classes
- [x] create backend classes
- [x] create mobile app entities and sync outbreak status
- [x] create new outbreak configuration view
- [x] list outbreak status in table (get all Outbreaks from backend; add column for each disease, add row for each region, when rendering filter outbreaks by disease and region and sum the data)
- [x] use buttons for editable regions
- [x] create edit form for a region and disease
- [x] persist data
- [x] create tests
- [x] create history table

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Please have a look at the mockup:

List of all the states the current user can access. For surveillance supervisors it will be a single state, for national users it will be all states.

The columns reflect all diseases available in SORMAS.

![ui_config_-_outbreak](https://user-images.githubusercontent.com/23217632/34838508-a65d1f12-f6fe-11e7-82ac-3b49c5c6ff92.png)

When the user clicks a cell in the table a popup opens that allows him to edit the outbreak status for all LGAs of the selected state and disease. The button on the top-right allows to set the outbreak status for all LGAs at once:

![ui_config_-_outbreak_-_edit](https://user-images.githubusercontent.com/23217632/34838509-a69ac506-f6fe-11e7-8d70-34e79296894d.png)

Interactive mockup: https://app.moqups.com/symeda/3NUENEwuOE/view/page/aa77c43a1

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Please have a look at the mockup:

List of all the states the current user can access. For surveillance supervisors it will be a single state, for national users it will be all states.

The columns reflect all diseases available in SORMAS.

![ui_config_-_outbreak](https://user-images.githubusercontent.com/23217632/34838625-2053ede6-f6ff-11e7-8bd9-e0e6178e8201.png)

When the user clicks a cell in the table a popup opens that allows him to edit the outbreak status for all LGAs of the selected state and disease. The button on the top-right allows to set the outbreak status for all LGAs at once:

![ui_config_-_outbreak_-_edit](https://user-images.githubusercontent.com/23217632/34838509-a69ac506-f6fe-11e7-8d70-34e79296894d.png)

Interactive mockup: https://app.moqups.com/symeda/3NUENEwuOE/view/page/aa77c43a1

PS: Please note that the visual style is not based on the actual SORMAS theme because it was easier to mockup this way. The implementation will of course use the SORMAS theme.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Updated moqups - what do you think?

![ui_config_-_outbreak](https://user-images.githubusercontent.com/23217632/34878522-b4410a7e-f7aa-11e7-8985-4543d63741f6.png)
![ui_config_-_outbreak_-_edit](https://user-images.githubusercontent.com/23217632/34878523-b460e9e8-f7aa-11e7-8d78-429bac651f2a.png)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
This makes sense and is a good idea when selecting affected areas but Gerard says that same configuration should be done on the fields to allow supervisors to determine what fields to activate or deactivate however, there should be a default limited field state so that if the supervisor decides not to add or remove from the default list then the outbreak mode is ready to be used while selecting which LGAs or states are affected. Hope it is clear.

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym 
I have committed the api and backend changes.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] remove double headline of edit popup

**Comment by MartinWahnschaffeSymeda** [comment]
The final refactoring result is a bit different from the original idea. "critical" remains. See commit!

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym @bernardsilenou 
Hey guys 
I am currently in a EWARS WHO meeting and have learnt alot on the work they are doing on EWARS. We need to integrate this technology into SORMAS outbreak system. It is related to our github issue for alerts and thresholds. Please we need to prioritize this. It is quite easy and I think we can do this within one sprint. More information on this later. This information is found here. http://apps.who.int/iris/bitstream/handle/10665/274318/9789241514354-eng.pdf?ua=1
