### ISSUE TITLE
New fields for CSM [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#474]
Based on the outbreak line listing #459 new fields are needed for CSM:

- [x] case data: No. of valid Vaccine doses (0,1,2,99) -> discuss how to handle this and other vaccination fields
- [x] hospitalization: Rename "date of admission" to "date of visit or admission"
- [x] hospitalization: add field "Admitted to health facility?" (yes, no, unk) -> if yes show isolated and date of discharge
- [x] symptoms: new symptom "Bulging fontanelle" - not visible when age is 2 or above
- [x] data dictionary has to be updated

Tasks:

- [x] rename vaccination fields in web
- [x] create new vaccination fields in app, migrate data from old to new fields, remove getters and setters from entity, comment member fields and add a deprecated hint

**Comment by MartinWahnschaffeSymeda** [comment]
For measles and yellow fever we already have specific vaccination fields. I think we should do the same for CSM:

- [ ] "Received CSM vaccination" (vaccinated, unvaccinated, unknown)
- [ ] "Number of valid doses"

@dta16 Does the CSM vaccination have a specific name that should be used?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda  Just call it CSM vaccination.
