### ISSUE TITLE
Automatic APK files via MDM currently don't work

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#477]
@MartinWahnschaffeSymeda  We have an issue that the apk file gets corrupt whenever we want to upload a new version to the MDM to push an automatic update. Can you please add versionName on the Manifest.xml so we can upload the apk file without corruption. 

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
The AndroidManifest.xml does have a a android:versionName.
I have also verified this for the apk file in the deploy.zip of the latest release:

**Comment by MartinWahnschaffeSymeda** [comment]
The AndroidManifest.xml does have a param called android:versionName which is always set to the latest version.

I have also verified this for the apk file in the deploy.zip of the latest release:
https://github.com/hzi-braunschweig/SORMAS-Open/releases/tag/releases%2Fversion-0.12.1

Please make sure you are using the correct apk file.
What exactly does the MDM say?

**Comment by hzi-braunschweig** [comment]
Dear Martin,
The MDM corrupts the apk file when we try to upload it for automatic push updates. I will check again. Can you send me a verified signed apk/ maybe that should work

Tom-Aba Daniel (B.Sc MPH)
Department of Epidemiology
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de<mailto:Daniel.Tom-aba@helmholtz-hzi.de>
EXT: 05316181-3124
