### ISSUE TITLE
Make app version more independant from server version [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#478]
Since updating the mobile app to the latest version is some work, we should make sure that this only has to be done, when there is a technical need for it. Currently the version has to be exactly the same - this needs to be changed. Likely we need an additional version for the api or a method that defines which versions are convertible.

Implementation:

- [x] add isCompatibleToApi(appVersion) to server InfoResource - implementation should use a minimal compatible version and include SNAPSHOT versions
- [x] use this method to check in app whether it's ok to sync
- [x] write a test that ensures that an old version is incompatible and the same version returned by getVersion() is compatible (do this by manipulating the MINIMUM_REQUIRED_VERSION string)

**Comment by MateStrysewskeSym** [comment]
- [ ] add test case where the appVersion is malformed
- [ ] make matchAppAndApiVersion method private, add public method without parameter
- [ ] rename exception back to "ApiVersionException"
- [ ] add comment to RetroProvider why method is called (-> throws exception that is then handled in UI)
