### ISSUE TITLE
Server down!!!

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#481]
![image](https://user-images.githubusercontent.com/19344651/35050073-3bd603c2-fba2-11e7-89f7-afac0396ab82.png)

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Please don't post server instance specific stuff here. Only specific bugs and requirements.

In addition I wasn't notified about this by github and saw it just now...
