### ISSUE TITLE
Test result filter under Samples Directory [1]

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Open#482]
Include test result filter under samples directory to allow filtering cases by result status e.g. positive, negative, etc... @MartinWahnschaffeSymeda @dta16

**Comment by MartinWahnschaffeSymeda** [comment]
We also need the case classification, so it's possible to identify cases with missing classification.

Tasks:

- [ ] add filter button for the test result
- [ ] add filter button for the case classifcation (no column)
- [ ] add SampleCriteria and use it for filtering (see other criterias for reference)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Rename "Case sample list" to "Case"
