### ISSUE TITLE
Define which data should be send to the mobile app (informant & officers) [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#49]
Example: When an officer is assigned to a contact task he needs to get access to the referenced contact as well and this probably also includes the case referenced by the contact.

Solution A would be to give the officer only access to data he is somehow assigned to (as described in the example). 

Solution B is to make all data of the officer's regional area (LGA) available on the phone. In this scenario the list of cases, contacts and events should by default filter to the entries of the officer.

Define the rules that define which data is send to a phone for the following items:

- [x] Cases
- [x] Contacts
- [x] Events
- [x] Tasks
- [x] Persons

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda  Solution B is to make all data of the officer's regional area (LGA) available on the phone. In this scenario the list of cases, contacts and events should by default filter to the entries of the officer.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda  Please note that this is for the contact officers/surveillance officers and ofcourse the supervisors. The excerption rule is the hospital informant. Only solution A applies to Hospital information @gstephan30

**Comment by StefanSzczesny** [comment]
Definition:
informant:
- [ ] all data associated to the facility (cases)
officers (all): 
- [ ] all data associated to the LGA (cases, events)
general:
- [ ] all data that is created by the user
- [ ] all data associated to the above data (contacts, tasks, persons, visits, symptoms, samples)
* time period is not needed for prototype

**Comment by StefanSzczesny** [comment]
There are sync issues while loading event from task side. Moved this from #67.
 - [ ] check event ID in task list
 - [ ] check link to event from task

**Comment by StefanSzczesny** [comment]
Moved the refresh after saving (push to server-side) matter from issue #68.
 - [ ] think about a all over refresh after saving concept

**Comment by MartinWahnschaffeSymeda** [comment]
In addition to the stuff above I have done the following:

- [x] add health facility to informant (backend, dto, ui, app)
- [x] include user in person rest sync
- [x] persons of cases and contacts
- [x] visits of the contacts persons
- [x] tasks of cases, events, contacts

the tasks "sync everything" und "unified refresh concept" should probably put into a new issue in the backlog.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] create docu file that explains what is synced

**Comment by MartinWahnschaffeSymeda** [comment]
See https://github.com/hzi-braunschweig/SORMAS-Open/blob/development/sormas-backend/doc/UserDataAccess.md for the documentation.
