### ISSUE TITLE
Rebuild app user interface based on new designs

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#490]
@sampsonorson 
We would like to integrate you into our development process.

This issue is as basis for your work on the new app design - feel free to add addtional ones. It would be great to see what still has do be done and how you are progressing. I hope this will make it easy to plan and do the integration.

**Comment by MartinWahnschaffeSymeda** [comment]
@sampsonorson please push your latest development state to github, so we can get an impression on what is still missing and how we can assist best.

**Comment by MateStrysewskeSym** [comment]
Merge will be done now in #558
