### ISSUE TITLE
Failed login pulls data from old server connection [1]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#495]
1. Login
2. Change server URL
3. Use wrong login data -> synchronization is apparently done with old URL and old login data

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda Couldn't reproduce this, could you please have a look into it?

**Comment by MartinWahnschaffeSymeda** [comment]
user name and password was not properly reset. In addition set, get and clear of username+password was not threadsafe.
