### ISSUE TITLE
Error message "Case cannot be saved due to internal error"

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Open#499]
The error message above continues to pop up and does not allow user to save case data being entered. 
This is happening on the mobile app, Informant's logon/interface. Kindly help resolve.

**Comment by MartinWahnschaffeSymeda** [comment]
This is very likely related to #503 (which I extracted from reported errors on google analytics).
It basically goes down to a synchronization problem that leads to damaged data remaining in the device.
#503 is fixed now and will be part of the upcoming release.
