### ISSUE TITLE
Complete the case definitions in the DataDictionary

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#50]
See https://docs.google.com/spreadsheets/d/1BA_RjM-ZhxFrzpAJdv0UVGhicHXNP6JnPBA-xzdrQKs/edit#gid=466434037

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda The case definitions have been completed in the data dictionary google sheet https://docs.google.com/spreadsheets/d/1BA_RjM-ZhxFrzpAJdv0UVGhicHXNP6JnPBA-xzdrQKs/edit#gid=466434037
