### ISSUE TITLE
Refactor PersonIndexDto and repair PersonSelectField

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#502]
Cause: Invalid cast from PersonIndexDto to PersonReferenceDto in PersonSelectField

- [ ] refactor PersonIndexDto
- [ ] fix bug

**Comment by MartinWahnschaffeSymeda** [comment]
multiselect does not work for person, because getting all persons requires multiple querries and we currently don't have an abstraction for this
