### ISSUE TITLE
Export full database to CSV files [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#507]
Users should be able to extract data directly from the database into CSV files. This allows them to extract any information in the needed way.

- [x] The files need to be packaged in a zip-file and then offered as a download.
- [x] Add new view "export" to the statistics section
- [x] Allow users the select which tables they want to export. Indent tables based on their hierarchie (e.g. epidata is indented in relation to cases and epidataburial in relation to epidata). Infrastructure should be seperated by another label. Don't include users

Exporting can be done using "COPY (SELECT * FROM cases) To '/tmp/cases.csv' WITH CSV DELIMITER ';';" (see https://stackoverflow.com/questions/1517635/save-pl-pgsql-output-from-postgresql-to-a-csv-file)

Tasks

- [x] Represent tables with enum - including hierarchie (getParent method)
- [x] Symptoms needs two entries: case symptoms and visit symptoms
- [x] for each we need a display name, a file name and a query
- [x] user right to access the view: give to national user and admin
- [x] export all selected entries into a temp folder, then create zip file

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Should national observers also be able to export the full database?

**Comment by hzi-braunschweig** [comment]
No. not at all ☺. This also applies to state observers

Thanks

Tom-Aba Daniel (B.Sc MPH)
Department of Epidemiology
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de<mailto:Daniel.Tom-aba@helmholtz-hzi.de>
EXT: 05316181-3124

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig This would mean that **state** observers are allowed to export the COMPLETE database. I don't think this is a good idea.

**Comment by hzi-braunschweig** [comment]
No I mean, the state observers should not be allowed to do so as well. National and state observers CANNOT export database.




Tom-Aba Daniel (B.Sc MPH)
Department of Epidemiology
Helmholtz Centre for Infection Research (HZI),
Braunschweig, Germany
Email: Daniel.Tom-aba@helmholtz-hzi.de<mailto:Daniel.Tom-aba@helmholtz-hzi.de>
EXT: 05316181-3124

**Comment by MartinWahnschaffeSymeda** [comment]
Oh, sorry - I got confused by the state observers. Got the point now. Thanks!

**Comment by MateStrysewskeSym** [comment]
- [ ] download button does not work
- [ ] add static strings (TABLE_NAME) to entities and use them in DatabaseTable enum
- [ ] use Path.resolve to make sure that export path and file name are correctly combined, combine path and file name parameters in sql function
- [ ] rename "blubb" in DatabaseExportView
