### ISSUE TITLE
Create mockup for supervisor dashboard

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#51]
The current moqup still is mixed with reporting components:
https://app.moqups.com/dta16/J6Y5spmqrH/view/page/ab9bf07f6?ui=0

- [x] Reduce the moqup to what is needed for the prototype
- [ ] Define what exactly is shown on the map

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda  @StefanSzczesny  I have reworked the dashboard and this is the new link https://app.moqups.com/dta16/J6Y5spmqrH/view/page/a34e9f40c?ui=0 it has less reporting components.

**Comment by MartinWahnschaffeSymeda** [comment]
Tickets for all the three components (map, epi curve, sitation report) have been created:
https://github.com/hzi-braunschweig/SORMAS-Open/issues?utf8=%E2%9C%93&q=label%3ADashboard%20
