### ISSUE TITLE
Facility missing from this states

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Open#511]
This Health facility are not reporting on SORMAS
Edo State
LGA-Esan
Health facility-Irrua specialist teaching hospital(ISTH) 
Enboyi State
LGA-Abakilike
Health facility-Federal teaching hospital Abakilike(FETHA)

**Comment by hzi-braunschweig** [comment]
@foyiri For now, you can use the "other health facility" function to add new health facilities.
