### ISSUE TITLE
Laboratory to be added to the list 

### ISSUE THREAD

**Issue by foyiri** [hzi-braunschweig/SORMAS-Open#515]
Ahmad Sani Yariman Bakura Specialist hospital(AYBSH), Gusau
Katsina state public health laboratory(SPHL)
Federal medical centre katsina
Comprehensive Health Center Laboratory  Daura  CHC
General hospital laboratory katsina
Comprehensive Health Center Lab oratory Funtua (CHC)

**Comment by foyiri** [comment]
This Laboratory are yet to be added to the laboratory list it needed urgent

**Comment by hzi-braunschweig** [comment]
@foyiri I will update it now

**Comment by foyiri** [comment]
Am also not clear with the request regarding admin add functionality for facility and for laboratory
