### ISSUE TITLE
It should be possible to deselect the occupation [0.5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Open#517]
Hi,
 A case was created with occupation as student and saved. I want to cancel and leave the field for accupation as blank ie "missing" because the occupaton was was not initially recorded in the investigatiion file,.
I want to correct the field and leave it blank but ther is no option to do that.

This applieds to most of the filed.

We need to include a blank option for all the field.

Best,
Bernard

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] the vaadin field factory for enum based fields needs to allow null select
