### ISSUE TITLE
test apk with new mobile version for video screencast for trainign

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#518]
@sampsonorson  @MartinWahnschaffeSymeda 
Hi Guys, 
Please can I get a  test apk that I can use to quickly create a screen cast for the informant and the surveillance officer. It is urgent and very important because it would help the users understand the new UI design. @sampsonorson  you said you would send something to me yesterday. Any updates from your end? we would like to begin screen cast today. 

Thanks and looking forward to a favorable response

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
Hi Guys,
Thanks Martin for setting up my local testing environment on SORMAS. I have no issues with the local SORMAS server but I cant seem to log into the rest API via the ip address. I get a connect timeout. Can you please assist me on this? I use the following ip address and port http://172.18.80.254:6080/sormas-rest. I make sure both tablet and laptop are connected to the same wifi. 

Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig Please try the following:

1. open the exact same address on your web browser on your PC/laptop. Does this work?
2. do the same with the browser on your mobile phone. Does this work?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda I tried the same link on the web browser and it didnt work

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig But http://localhost:6080/sormas-rest works?
Please verify that 172.18.80.254 is really your local IP address. You should always be able to access your local IP...
