### ISSUE TITLE
SQL function to easily add new health facilities to the database

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#519]
Params: facility name, isLaboratory, region name, district name, community name (optional), latitude (optional), longitude (optional)

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig 
I have create a SQL function that allows you to easily create new health facilities and laboratories from the backend.

```
add_health_facility(
    name,
    islaboratory,
    regionname,
    _districtname, // can be null for labs
    _communityname, // can be null
    _city, // can be null
    _latitude, // can be null
    _longitude) // can be null
```

usage example for a health facility:
`SELECT add_health_facility('new health facility', false, 'Abia', 'Aba North', 'Ariaria Ward', 'Aba', 7.356480, 5.125462);`

usage example for a lab:
`SELECT add_health_facility('new lab', true, 'Abia', null, null, 'Aba', null, null);`

You can already use it on sormas.org.ng for #511 and #515

**Comment by MateStrysewskeSym** [comment]
- [ ] return an error when district or community is not found although parameter was passed
