### ISSUE TITLE
Ebola should not be default disease

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Open#520]
Default diseaes in sormas in Ebola, this leads to errors. I suggest it should be blank and sormas should force users to choose the disease before saving, it should not allow users to save a bland disease.
I made this erro myself when i wanted to creat a monkeypox case but it was saved as ebola, good that i was an admin to be able to change the disease name.
Best,
Bernard

**Comment by MartinWahnschaffeSymeda** [comment]
Good point ...
