### ISSUE TITLE
Design/program a printable version of SORMAS data into a form that looks like the IDSR form

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#524]
Design/program a printable version of SORMAS data into a form that looks like the IDSR form

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym

**Comment by MartinWahnschaffeSymeda** [comment]
With the given statistics export options this is no longer needed.
