### ISSUE TITLE
Automatic update of case outcome and person’s condition [5]

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Open#525]
I went to cases and search all Lassa cases that are death, I found a case. When I open to look at the case data, The present conditiion was death but the outcome was "not yet classified". This is inconsistecy in my openion

My suggestion is that if the present condition of a case is "death", then the outcome should authhomatically be changed to"deceased".
If outcome is changed to "diceased" then present condtion should also be changed to  death.
The defauld outcome of "Not yet classified" is correct but should be linked with the present condition such that is the present condition is changed, then the outcome should also change accordingly.
Maybe Daniel and Gérard will have to confirm this.
Best,
Bernard

**Comment by hzi-braunschweig** [comment]
@bernardsilenou Please do not put real case information on github. 

Thanks

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda We have to discuss whether we want to do this before we take care of the automatic case classification.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] when a case outcome is set to deceased the related person should be set to dead (cause is the disease). This can also lead to the next point:
- [ ] when a case outcome is set back to recovered or no outcome yet, the related person should be set to alive (if dead)
- [ ] when a person condition is set to dead or burried the related no outcome and unknown cases have to be set to deceased. Disease is not relevant.
- [ ] when a person condition is set to alive, the related deceased cases have to be set to o outcome yet.
- [ ] this logic should be done in the server's facade logic **not** in the app
- [ ] in the app the logic should be done only for the edited case
- [ ] the app synchronization logic has to take into account that pushing persons may require to pull cases again before pushing them

@hzi-braunschweig Please have a look at the above rules and let us know if this is correct.

**Comment by MartinWahnschaffeSymeda** [comment]
Synchronization process was already working correct. During sync it pulls and pushes for each single entity, so after syncing the modified person the case changed on the server side is automatically transfered.

TODO:
- [ ] edit tabs currently are not updating to the changed value
- [ ] check if sync merges cases correctly - it should actually not be necessary to send it to the server.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] when case outcome is set to deceased the persons cause of death should be set to the disease

**Comment by MateStrysewskeSym** [comment]
- [ ] fix cause of death fields appearing even if the condition is set to alive
