### ISSUE TITLE
Surveillance Officer can't create new case (0.16.0)

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#539]
When trying to create a new case the screen get's white, synchroinzation is started and then the app restarts.

We need to create a hotfix for 0.16.0 and for 0.17.0.

Happened for users TZA26T-PWB4LT-VL45HE-HKL7KPPE and QKL3BM-TRQ6AF-MI2YKX-4BQOKN7I

> RuntimeException - Root cause: java.util.ConcurrentModificationException - Stack trace: android.app.ActivityThread:performLaunchActivity:2927 -> android.app.ActivityThread:handleLaunchActivity:2988 -> android.app.ActivityThread:-wrap14:-1 -> android.app.ActivityThread$H:handleMessage:1631 -> android.os.Handler:dispatchMessage:102 -> android.os.Looper:loop:154 -> android.app.ActivityThread:main:6682 -> java.lang.reflect.Method:invoke:-2 -> com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1520 -> com.android.internal.os.ZygoteInit:main:1410 - Root cause stack trace: java.util.ArrayList$Itr:next:831 -> de.symeda.sormas.app.backend.facility.FacilityDao:getHealthFacilitiesByDistrict:71 -> de.symeda.sormas.app.caze.CaseNewForm:onCreateView:72 -> android.support.v4.app.Fragment:performCreateView:2080 -> android.support.v4.app.FragmentManagerImpl:moveToState:1108 -> android.support.v4.app.FragmentManagerImpl:moveToState:1290 -> android.support.v4.app.BackStackRecord:run:801 -> android.support.v4.app.FragmentManagerImpl:execPendingActions:1677 -> android.support.v4.app.FragmentController:execPendingActions:388 -> android.support.v4.app.FragmentActivity:onStart:604 -> android.support.v7.app.AppCompatActivity:onStart:178 -> android.app.Instrumentation:callActivityOnStart:1256 -> android.app.Activity:performStart:6959 -> android.app.ActivityThread:performLaunchActivity:2890 -> android.app.ActivityThread:handleLaunchActivity:2988 -> android.app.ActivityThread:-wrap14:-1 -> android.app.ActivityThread$H:handleMessage:1631 -> android.os.Handler:dispatchMessage:102 -> android.os.Looper:loop:154 -> android.app.ActivityThread:main:6682 -> java.lang.reflect.Method:invoke:-2 -> com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1520 -> com.android.internal.os.ZygoteInit:main:1410

Probably related:

> ConcurrentModificationException - Root cause: java.util.ConcurrentModificationException - Stack trace: java.util.ArrayList$Itr:next:831 -> de.symeda.sormas.app.backend.facility.FacilityDao:getHealthFacilitiesByDistrict:71 -> de.symeda.sormas.app.component.FacilityChangeDialogBuilder$2:onItemSelected:101 -> de.symeda.sormas.app.component.SpinnerFieldListener:onItemSelected:22 -> android.widget.AdapterView:fireOnSelected:1312 -> android.widget.AdapterView:dispatchOnItemSelected:1301 -> android.widget.AdapterView:-wrap1:-1 -> android.widget.AdapterView$SelectionNotifier:run:1268 -> android.os.Handler:handleCallback:751 -> android.os.Handler:dispatchMessage:95 -> android.os.Looper:loop:154 -> android.app.ActivityThread:main:6682 -> java.lang.reflect.Method:invoke:-2 -> com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1520 -> com.android.internal.os.ZygoteInit:main:1410 - Root cause stack trace: java.util.ArrayList$Itr:next:831 -> de.symeda.sormas.app.backend.facility.FacilityDao:getHealthFacilitiesByDistrict:71 -> de.symeda.sormas.app.component.FacilityChangeDialogBuilder$2:onItemSelected:101 -> de.symeda.sormas.app.component.SpinnerFieldListener:onItemSelected:22 -> android.widget.AdapterView:fireOnSelected:1312 -> android.widget.AdapterView:dispatchOnItemSelected:1301 -> android.widget.AdapterView:-wrap1:-1 -> android.widget.AdapterView$SelectionNotifier:run:1268 -> android.os.Handler:handleCallback:751 -> android.os.Handler:dispatchMessage:95 -> android.os.Looper:loop:154 -> android.app.ActivityThread:main:6682 -> java.lang.reflect.Method:invoke:-2 -> com.android.internal.os.ZygoteInit$MethodAndArgsCaller:run:1520 -> com.android.internal.os.ZygoteInit:main:1410 - User: QKL3BM-TRQ6AF-MI2YKX-4BQOKN7I

@MateStrysewskeSym Please have a look into this first thing tomorrow.
I will also look into the other bugs on google analytics. Daniel reported that moving a case also doesn't seem to work for him.

**Comment by MateStrysewskeSym** [comment]
The reason very likely is that we remove items from the list of facilities while iterating over it with a for loop. My suggestion is to adjust the query to exclude laboratories if needed (either by a separate method or a parameter) and get rid of the manual removal.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig sormas.org.ng database is fixed, so case creation should work for the officer again after synchronization.
