### ISSUE TITLE
Use ActivityState for up-navigation [3]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#54]
- [x] check concept in regard of Activity-Lifecycle https://developer.android.com/training/basics/activity-lifecycle/recreating.html
- [x] should behave like android back navigation
- [x] collect all occurrences
- [x] plan for refactoring

**Comment by StefanSzczesny** [comment]
https://developer.android.com/guide/components/activities/activity-lifecycle.html
https://developer.android.com/training/appbar/up-action.html
https://developer.android.com/guide/components/activities/tasks-and-back-stack.html


States wich will used in activity lifecycle:
@Override
    protected void onSaveInstanceState(Bundle outState) {
	 super.onSaveInstanceState(outState);
    }

    @Override
    protected void onRestoreInstanceState(Bundle savedInstanceState) {
	 super.onRestoreInstanceState(savedInstanceState);
    }

**Comment by StefanSzczesny** [comment]
while leaving:
https://developer.android.com/reference/android/app/Activity.html#onRestoreInstanceState(android.os.Bundle)

then finish() and get the bundle in onResume()

**Comment by hzi-braunschweig** [comment]
Hey Stefan. I am working on the mobile app and I cannot see the investigation button or done or not executable buttons on the task menu or case menu. Please check this.

thanks
