### ISSUE TITLE
"Template not available" for case import on sormas.symeda.de

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#546]
Was probably deleted at midnight.

**Comment by MateStrysewskeSym** [comment]
- [ ] create "sormas-generated" folder, same access rights as sormas-temp, save import templates there

**Comment by MateStrysewskeSym** [comment]
- [ ] add comment to generated files path that it should not be the same like temp files path
