### ISSUE TITLE
Red ribbon error occurs on entering case with "other health facility" 

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Open#559]
Red ribbon error bar as seen in the pic appears when you try to enter a case with the same name as an existing case in the system. The constraint dialogue appears asking to "create or choose case", when you create as new case, the error appears. 
This also pops up when you try to enter a case's facility as "other health facility".  

![image](https://user-images.githubusercontent.com/35563508/38503097-0ad75dbe-3c09-11e8-9c7a-fbb589d21847.png)

**Comment by MateStrysewskeSym** [comment]
Very likely fixed with #562
