### ISSUE TITLE
Set "outcome status" to default blank instead of "no outcome yet" on the case directory

### ISSUE THREAD

**Issue by Chinedar** [hzi-braunschweig/SORMAS-Open#560]
Kindly set case outcome status to default "blank". 

Currently defaults to "no outcome yet" and this affects the case count for data entry officers.

**Comment by Chinedar** [comment]
thanks

**Comment by MartinWahnschaffeSymeda** [comment]
@Chinedar @hzi-braunschweig 
Can you please give some more details on where the case count is affected and why this should (not) happen? "no outcome yet" seems to be perfectly correct from my point of view, since there is no outcome yet...

**Comment by Chinedar** [comment]
Yes "no outcome yet" is perfect but at the moment it appears first instead
of the blank default which means nothing has been assigned. Because "no
outcome yet" being one of the options for that variable, filters and hides
such cases such that they are not able to find them on the search.

The default should be set to "blank" not "no outcome yet"


Thanks.

**Comment by Chinedar** [comment]
Dear Mate,

This still sets the option "no outcome yet" as the first and default option
on the outcome variable.

Can this be set to "blank" as the default option that appears?

Thanks.

On Wed, Apr 18, 2018 at 9:44 AM, MateStrysewskeSym <notifications@github.com

**Comment by MateStrysewskeSym** [comment]
Hey Chinedar,

you will have to wait for the next release until this takes effect. When the new SORMAS version is released on the official server, the filter will be blank by default.

Best regards!

**Comment by Chinedar** [comment]
Thanks!!!
