### ISSUE TITLE
Error when a date filter field is empty

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#561]
When e.g. leaving the epi week to field empty, an error is thrown and the data is not filtered.

- [x] display a warning if one of the dates is missing

**Comment by MateStrysewskeSym** [comment]
- [ ] make sure that date filter in case list works completely empty

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] make hint orange/yellow
