### ISSUE TITLE
Add default time filters to the dashboard [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#567]
This will allow users to easily filter to a relevant time period without having to pick the dates from both drop downs.

- [x] Filters: today, yesterday, this week (default), last week, this year, last year, custom
- [x] Should look the same as the investigation status filters in the case directory.
- [x] Custom opens a popup that allows to selected the period. When this is done "custom" is replaced with the time string. "apply filters" will no longer be necessary (it's bascially replaced with an ok button in the popup).
- [x] Fix between methods in DateHelper returning the wrong number
- [x] Add tests for these methods

**Comment by MateStrysewskeSym** [comment]
- [ ] make space between date buttons (probably custom style with smaller spacing)
