### ISSUE TITLE
Mockups for statistics [1]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#569]
Create a mockup that visualizes the following aspects of #541 . See https://survstat.rki.de/Content/Query/Create.aspx

- [x] Sections: Filters, Displayed attributes & display options, Results
- [x] How is a new filter added (list of filter options)
- [x] Example for a time filter (month of year + select for onset/reception/report)
- [x] Place filter (region + district)
- [x] Example for a person filter (age-group)
- [x] How to pick an attribute
- [x] How to define display options (e.g. incidence)
- [x] Result table (+ drop down to pick table, column chart, ..., map) + export button

**Comment by MateStrysewskeSym** [comment]
Moqup: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a1fa312c1
