### ISSUE TITLE
App 0.18 (.0 and .2) can't sync with server 0.19

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#571]
@MateStrysewskeSym 
App says "could not synchroize because the app version is newer than the server version".

Had to rollback sormas.symeda.de to version 0.18.2, because they are doing a training now.

**Comment by MateStrysewskeSym** [comment]
- [ ] make sure to abort compatibility check for "too new" when one of the server version parts is higher than the respective app version part
- [ ] add unit tests that explicitely call isCompatibleToApi with the third and second version digit differing from the api version
