### ISSUE TITLE
Strange occurence when contact is converted to a case

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#573]
@MartinWahnschaffeSymeda @MateStrysewskeSym 
When a contact officer creates a case for a contact and the new case is created, the user changes automatically from contact officer to informant. I did it twice and had to re log in again. What could be theh cause of this. 

Also the guys training said when they want to create a case for a contact, the ward and health facility drop down is blank

![image](https://user-images.githubusercontent.com/19344651/39006368-2563be14-4403-11e8-9bed-84f0d049ccb4.png)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @MateStrysewskeSym 

This is still an issue as i could not create a case for this contact. please can you look into this. I logged in as JameDoe contact officer on symeda server. Check analytics. Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
Steps to reproduce: Login as Informant, Login as Officer

**Comment by MartinWahnschaffeSymeda** [comment]
Problem is caused by contact officer not having the right to create a new case

- [ ] allow contact officer to create and edit a case
- [ ] allow surveillance officer and supervisor to convert a contact
