### ISSUE TITLE
Statistics refactorings and improvements [5]

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#601]
## UI & usability

- [x] For 1 year intervals, only show the year without range
- [x] Change caption of chart visualization options (Type -> Chart type, find proper replacement for rows and columns)
- [x] move options to visualization area, remove options area
- [x] remove step numbers
- [x] stacked column chart is not drawn when no groupings are selected
- [x] make grid size undefined (should never have more width than it needs)
- [x] make grid unsortable
- [x] refresh district filters when region filters changes (e.g. remove districts from other regions)

## api

- [x] add attribute group parameter to attribute constructor, let attribute group enum build list of attributes in this group

## backend

- [x] add helper method to DataHelper that checks if a collection is null OR empty. Replace usages in facade method -> use CollectionUtils.isNotEmpty instead
- [x] add comments to queryCaseCount method - summary at the start explaining the steps to build the query (including an example query), add step markers
- [x] add StatisticsGroupingKey interface and also implementations Quarter and Year
- [x] all StatisticsGroupingKey attribute instance types need to implement toString, equals, hashCode and compareTo (Comparable)
- [x] queryCaseCount should replace querried grouping objects (e.g. "201712") with StatisticsGroupingKey (e.g. MonthYear) -> do this in a seperate method

## sormas-ui

- [x] adjust visualization logic to use StatisticsGroupingKey (buildHeader, etc. is no longer needed)
- [x] add explicit StatisticsFilterRegionDistrictElement
- [x] see if StatisticsFiterComponent and ..Element can be combined
- [x] Switch button for visualization (swap rows and columns)

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Workarround: I haven given all columns (but the total) a maximum width.
