### ISSUE TITLE
Case map on supervisor dashboard [5]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#62]
see https://app.moqups.com/dta16/J6Y5spmqrH/view/page/a34e9f40c?ui=0

first draft:
- [x] dots for cases (based on health facility): colorize by classification (confirmed red, suspected yellow, probable grey) 
- [x] define geo coordinate for contact
- [x] define geo coordinate for event

later:
- dots for contacts: colorize by days of no follow-up ()
- dots for events
- regional analyses on incidence # examples by Salla

source: https://github.com/hzi-braunschweig/SORMAS-Open/issues/51

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 A few questions:

1. I suppose a case is shown at the geo coordinates of it's health facility. Is this correct? If so, do you have geo coordinates for all the health facilites? 
2. Events should probably be shown at the geo coordinates of the event location (the address the event took place). Right?
3. What geo coordinates are used for the contact? Coordinates based on the address of the contact person?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda 
1. Ideally, all health facilities should be geo coded and used on SORMAS but the unfurtunate truth is that It is very difficult to get the exact approximated coordinates for all health facilities. This is a major project on its own. Having said that, I feel it is important to have geo coding for every case or contact person created. This gives us the ability to observe clustering of cases and contacts. If you have cases mapped by HFs then you will have a lot of overlapping dots if several cases belong to one HF and it wont make sense for action from a spatial analysis point of view. So let all cases and contacts created by the officers be geo coded at the point of creation. If its in the HF then that is good but some cases are created outside the HF for instance Event rumors. Some cases might be created at Airports, or HFs close to the airport or other geographical locations which are not related to the HFs. 

2. For events, I agree with you, it is best to use the geo coodinates of the event location but it should also be generated when the rumor event or rumor persons are created.

3. For the coordinates, when a contact is created at home or in the hospital, the location of contact creation will be the geo coordinates based on the home addresses of the contacts. This is for new contacts. As for contact visits, each day that a contact is visited, the geo coordinates is included with each visit. So it will be possible to view contact visits clusters on a map over a period of time which can be spatially analysed for action.

**Comment by hzi-braunschweig** [comment]
@stoikkanen @gstephan30

**Comment by StefanSzczesny** [comment]
* Further clarification on 2. (event): Use the centroid of the event's LGA (which is a required field).
* contact color: green: visited within 24 hours, yellow: visited within 48 hours, red: others
* contact & case: use report geo coordinates
* click on case/contact/event to open it

**Comment by MartinWahnschaffeSymeda** [comment]
Other stuff is part of #126 and #127
