### ISSUE TITLE
Event persons UI [2]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#66]
- [x] event persons grid
- [x] update "add person" mockup: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a30e0ef5e
use the component that allows the selection of existing persons within the form
show person creation/edit form as second step
- [x] "add person" form: kind of involvement and person
- [x] edit person in popup
- [x] create new case from event person
- [x] code review

**Comment by StefanSzczesny** [comment]
Define when a case should be shown in the event persons list (disease, time overlap)

**Comment by MartinWahnschaffeSymeda** [comment]
Improvements as discussed in review:

- [ ] date & time of report: show time
- [ ] layout: move officer line to the bottom (see https://app.moqups.com/symeda/3NUENEwuOE/edit/page/af5b4329c)
- [ ] LGA required
- [ ] surveillance officer required
- [ ] filter surveillance officer list by selected LGA
- [ ] default value for state (take from creating user)
- [ ] Kind of involvement -> text + "Involvement description"

**Comment by MateStrysewskeSym** [comment]
LGA is set to required but validation has issues, see #95

**Comment by MateStrysewskeSym** [comment]
Outsource select or create for event participant
