### ISSUE TITLE
Event persons list & create/edit in app [2]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#69]
- [x] list mockup based on UI mockup: https://app.moqups.com/symeda/3NUENEwuOE/edit/page/ad1380fa0
- [x] "create" & "edit" mockup
- [x] rest interface for event persons
- [x] "add person" creation process: define steps
- [x] check if the existing person selector can become a component

~~sync:~~ moved to #123
~~- [ ] sync event persons together with events (app)~~
~~- [ ] backend: sync event persons based on user roles~~
~~- [ ] create/update persons if needed (app)~~

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] display case status for persons that are a case (see https://app.moqups.com/symeda/3NUENEwuOE/edit/page/a1709a9ea)
- [ ] use same code as in getByPersonAndDisease and add comments that link between both. Also add a todo "add time context"
