### ISSUE TITLE
Generation of contact follow-up task (POS 4) [3]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#70]
During the disease dependent follow-up period of a contact the responsible contact officer has to do daily visits. The SORMAS system should automatically generate a task for each visit that reminds the officer to do the visit. 

- [x] update calculation of "follow-up until" based on existing visits
- [x] implementation of service method that is called every night. Goes through all contacts under follow-up and creates contact visit tasks, if they don't exist yet for the day
- [x] start time: 0:00; due time 23:59
- [x] assign to contact officer of contact. If not set use contact supervisor of state.

**Comment by MartinWahnschaffeSymeda** [comment]
Follow-up status suggestion
- [ ] make follow-up status read-only
- [ ] add buttons for "cancel" and "lost"
- [ ] add comment field for the follow-up status

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] contact officer only for follow-up diseases

**Comment by MartinWahnschaffeSymeda** [comment]
Done so far, but we still need discuss:

1. Should contact officer become a required field when edited by the contact supervisor?
2. How should we deal with the tasks when a person has multiple contacts assigned to different contact officers?
3. What should happen to the other contacts when one becomes a case?
4. What if there are multiple contacts for different diseases?
