### ISSUE TITLE
Task fixes (App & UI) [0.5]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#71]
- [x] creator comment -> supervisor comment
- [x] creator -> hide if empty
- [x] display status in app's list -> display below date
- [ ] check link in notification -> tasks sometimes link to wrong tasks in the app

**Comment by MateStrysewskeSym** [comment]
- "creator -> hide if empty" => does this mean that the reporting user should be hidden (e.g. because the task has been created automatically)?
- "display status in app's list" -> what exactly does this mean?
- "check link in notification" -> please specify

**Comment by MateStrysewskeSym** [comment]
Notifications are a general issue and need to be looked at separately. Comments are sometimes not displayed in the notification and notifications link to wrong tasks.

**Comment by MateStrysewskeSym** [comment]
see #100
