### ISSUE TITLE
Contact & visit fixes (app & UI) [2]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#74]
- [x] fix "was is same room"
- [x] new visit: default to today; add time (see #73)
~~app visit: lock symptoms when unavailable or uncooperative~~
~~ui visit: lock symptoms when unavailable or uncooperative~~
- [x] else OnsetDate mandatory (when cooperative)
- [x] proximity description: "if multiple pick the closest contact proximity"

**Comment by StefanSzczesny** [comment]
The way to implement a toggle for tabs in android ist very complex. 
http://stackoverflow.com/questions/10396321/remove-fragment-page-from-viewpager-in-android

There have to be fragments removed and this triggers also events. All these changes maybe have some unpredictable side effects. 
I would suggest to use the tab as it is for the pilot.

**Comment by StefanSzczesny** [comment]
it's ok for now that symptoms are not locked. But we need to add the following:

- [ ] when cooperative: all unconditional symptoms and temperature and source are required. Conditonal symptoms (e.g. bleeding of the gums) are only required if the associated symptom is set to yes)
- [ ] date of onset only required when cooperative and **symptomatic**

**Comment by StefanSzczesny** [comment]
Implementation suggestion for the "symptoms required" problem:
Add an explicit method to the SymptomsForm (web and app) that sets the field's required state for this situation.

- [ ] In addition we need unit tests for this - at least for the web. Create a SymptomsForm, manipulate it's fields and check if the resulting required states match the expectations
- [ ] update the data dictionary with the specifics on the "required" conditions

**Comment by MateStrysewskeSym** [comment]
Correlation of fever and temperature has been added to Vaadin app, needs future work when general validation is reworked.
