### ISSUE TITLE
Relation for contact person [0.5]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#75]
Defines how a contact person relates to a case person (e.g. parents, ...)

step 1:

- [x] define types of relation (see https://docs.google.com/spreadsheets/d/1BA_RjM-ZhxFrzpAJdv0UVGhicHXNP6JnPBA-xzdrQKs/edit#gid=764973530)

step 2 (Symeda):

- [x] add to contact entity
- [x] add to UI form
- [x] add to app form

**Comment by stoikkanen** [comment]
See the data dictionary
