### ISSUE TITLE
Epidemiological curve on supervisor dashboard

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#77]
See https://app.moqups.com/dta16/J6Y5spmqrH/view/page/a34e9f40c?ui=0

- [x] Define how the number of cases for each day is calculated

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Please define how the number of cases for each day is calculated for the bar chart.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda  Hallo Martin, The number of cases for each day shown on the bar chart is cumulative as of the present day. E.g Total Number of Ebola Cases as of today (12.12.2016): Confirmed cases bar (12), Suspected cases bar (22), Probable Cases bar (2) etc. Where the bars refer to stratification based on Case status for each Bar on the Bar chart. Is this clear? @stoikkanen & @gstephan30 What do you guys think?

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda  I cant see any question!

**Comment by MartinWahnschaffeSymeda** [comment]
I marked this to remember that we need to discuss it. The label is renamed to "discuss" now.

**Comment by dta16** [comment]
Roger that.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] cases by date of report
- [ ] optionally group by week ("by day", "by week")
- [ ] bar grouped by current classification
- [ ] filter: start date, end date, disease
- [ ] default filter: show full weeks (this and the previous three). Leave remaining days of this week empty

**Comment by MartinWahnschaffeSymeda** [comment]
@Krisistis Based on Sallas comment above the cases will be shown by the date of report (alternatvely sympton onset) on the x-axis and grouped by the current classification.

**Comment by Krisistis** [comment]
Please use date of onset of symptoms instead of reporting date

**Comment by MateStrysewskeSym** [comment]
- [ ] find a way to fix the initial chart size
