### ISSUE TITLE
Situation Report Summary on supervisor dashboard

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#78]
![7e0c75c0-e8a5-11e6-8e2b-83af42eb3e77](https://cloud.githubusercontent.com/assets/23217632/25120329/de80dca8-241d-11e7-8a31-0c8de04dfca0.png)

Calculate each value for health workers and non-health workers:

- [x] same filter as for map and epi curve
- [x] Number of confirmed, probable, suspect and total cases by date of symptom onset
- [x] For each: number of health care workers (based on case person's occupation)
- [x] Deaths (confirmed and probable cases) by date of death
- [x] Number of contacts under follow-up (math follow-up period with filter period) + same number on last day of query period
- [x] Number of rumours and outbreaks by date of report
- [x] all values for previous period
- [x] arrows that show tendencies

Remarks:
- leave previous year's average out for now, since we don't have data anyway
- layout with the vaadin grid - the final solution doesn't have to look exactly like the draft
- build service methods that query for all needed data

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 What is the reference date used to filter cases by time period? Is it the date the case classification was done? Or the date the case was reported?
For Deaths the case's "date of death" is probably the relevant criteria?
For Dischared confirmed cases it's the date the case was discharged? Or some other data?

**Comment by StefanSzczesny** [comment]
@stoikkanen 
- [ ] define alls fields of the table(s)

**Comment by stoikkanen** [comment]
For the dashboard table I thought of something similar to this:

![image](https://cloud.githubusercontent.com/assets/24520043/22514023/448d407e-e89e-11e6-80e1-437e65d6d880.png)

The filter's used for the map and epicurve should be used also for the table. in the title line the length of  the query period is visible (in days). The second  column shows the situation during a query period of equal length but just before the actual query and the third would show the average from corresponding query periods during past years. This is a  vague attempt to incorporate  some  simple "outbreak detection" in the system and the arrows in the second and third column show the query periods rating relative to the past days or past years (only for cases and deaths). 

For the contacts under follow-up, we discussed previously, that actually only the data on the last query date is somehow comparable (the date should be placed on marked on dd.mm.yyyy). Maybe the cumulative number (i.e. the line above this with count 152) can even be removed.  

Please, feel free to ask and comment

**Comment by stoikkanen** [comment]
Aaand redo to add the Health care workers (HCWs):
![image](https://cloud.githubusercontent.com/assets/24520043/22515952/940aef88-e8a4-11e6-8d5d-9fbce8cb7ae0.png)
Phew, the table gets big. After reconsideration I would still like to keep everything in one table instead of multiple unlike our prior discussion
@StefanSzczesny @MartinWahnschaffeSymeda @dta16 @gstephan30 @Krisistis

**Comment by stoikkanen** [comment]
Based on today's discussion about the priorities w Gérard: 
the dashboard would be "nice to have" for the workshop, but instead of complicated maps, graphs and tables an epicurve and a simple table  from the whole query period would be enough:
# n of cases
##  grouping by sex, age group  and case definition
# n of deaths
## group by sex, age group case def
For the  workshop a rough age grouping can be applied, 0-14 y, 15-44y, 45-y  and then discussed further.

@StefanSzczesny @dta16 @MartinWahnschaffeSymeda @gstephan30 @Krisistis

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 @Krisistis Have you been able to define this one?
I'm not sure if a table or a diagramm is a better fit. Please also consider Salla's previous comment on limiting this n of cases and n of deaths, each grouped by sex, age, classification and give an example of what it should look like.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Salla was referring the limitation of the summary table to show for the workshop. So please lets use the example she gave earlier which is shown below but stratified by Number of Health worker/Non health worker
![image](https://cloud.githubusercontent.com/assets/19344651/25008340/b3637b38-2063-11e7-9117-c32917ace35b.png)

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] refactoring: extract into component
- [ ] Deaths: change total and hcw to match style of cases
