### ISSUE TITLE
Some Observation from Testing the Mobile app

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#79]
@MartinWahnschaffeSymeda @StefanSzczesny @MateStrysewskeSym 
**Comments from App**
1. Put date of case report beside each case (mobile app) case list
2. During input, user has to save at each new data entered before moving to next screen (mobile app)
3. When I click save, it is meant to take me back to main menu. (mobile app)
4. There is no main menu on the mobile app (global landing page is currently case list) very important (mobile app)
5. No date of report sent to the database after user has submitted data. (Web app)
6. Ability to search for a case from the case list. (Web app)
7. For a case record which has associated contacts, the responsible contact officer does not show either on the mobile app or on the web app. it is blank. It should show. (Web/mobile app)
8. All unrelated symptoms should be hidden. (Web/mobile app)
9. Add a column for contact status (converted to case, unconfirmed contact, not a contact etc) on the case contacts. (Web app) 
10. Please note. How long before a new task hits the mobile app??? (mobile app) 
11. During visit interview, once you save, it should go to the next page (symptoms and not contact data. it will confuse the user (mobile app)
12. I tested the mobile app and gave a temperature of 45 degrees Celsius and set all symptoms including fever to NO. I didn't get any restriction as Fever and temperature above normal should be the same. E.g. if a contact has fever then his temp should read greater that 37.8. Even if we have not done the alerts and triggers but this is a requirement field issue. if Fever is Yes, Temperature must be above 37.9. Then there is a statement on the follow up visit that 45 degrees is not symptomatic. Please note (mobile app)
12. A case who is still a possible case had contacts which was converted to a case. The system did not alert me that that contact who has just been converted to a case has a source case that is not even a confirmed suspected case or confirmed case. (Please note) (mobile app)

More observations on the way as testing is still being done. Thank you

Well done so far. @stoikkanen  @gstephan30

**Comment by MartinWahnschaffeSymeda** [comment]
On 4.: Should the app really have a main screen? Wouldn't it be better to always start in the Task screen? If a main screen is requiered: What should it look like?

**Comment by hzi-braunschweig** [comment]
[Landing Pages.pdf](https://github.com/hzi-braunschweig/SORMAS-Open/files/698831/Landing.Pages.pdf)
@MartinWahnschaffeSymeda @StefanSzczesny @gstephan30 @stoikkanen

**Comment by hzi-braunschweig** [comment]
[Landing.Pages.pdf](https://github.com/hzi-braunschweig/SORMAS-Open/files/702219/Landing.Pages.pdf)
@MartinWahnschaffeSymeda

**Comment by hzi-braunschweig** [comment]
*** Surveillance Supervisor***
* Notification alert once officer completes a given task (Background processes running prompt notification even if app is off)
* Email notification between Supervisors when tasks are given and exchanged. 
* Notification when Lab result is sent by Lab officer to supervisor. 
* Notification alert when contact of suspected or confirmed case becomes symptomatic (temperature >=38 celcius, Headaches, etc.)
* Notification alert when there is any form of case disposition from one status to the other. (Suspected case, confirmed case, not a case)
* Trigger alert when lab result is confirmed positive (Text notification, email notification, app notification) 
* Notification alert when a major change has been made to any case file
* Notification alert when a final classification has been assigned to a case.


***Surveillance Officer***
* Notification alert once supervisor generates a task (Background processes running prompt notification even if app is off)
* Notification alert via text message and app notification once a new case is created by Hospital informant and submitted.
* Notification alert via app notification when a change has been made to a case file still under investigation
* Notification alert when Supervisor has disposition a possible case to a suspected case or vice versa. 
* Notification alert when a final classification has been assigned to a case within an officer's jurisdiction. (feedback)



***Contact Supervisor***
* Notification alert once contact officer completes a given task (Background processes running prompt notification even if app is off)
* Email notification between Supervisors when tasks are given and exchanged. 
* Notification when Lab result is sent by Lab officer to supervisor. 
* Notification alert via text message and app notification once a new contact is created by contact officer and submitted.
* Notification alert when contact of suspected or confirmed case becomes symptomatic (temperature >=38 celcius, Headaches, etc.)
* Notification alert when there is any form of case disposition from one status to the other. (Suspected case, confirmed case, not a case)
* Trigger alert when lab result is confirmed positive (Text notification, email notification, app notification) 
* Notification alert when a major change has been made to any case file
* Notification alert when a final classification has been assigned to a case.

***Contact officer***
* Notification alert once supervisor generates a task (Background processes running prompt notification even if app is off)
* Notification alert via app notification when a change has been made to a contact file still under listing and classification
* Notification alert when Supervisor has disposition a possible case to a suspected case or vice versa. 
* Notification alert when a final classification has been assigned to a case within an officer's jurisdiction. (feedback)
* notification alert via app when a possible contact has been converted to a confirmed contact (Feedback)

***Case Supervisor***
* Notification alert once officer completes a given task (Background processes running prompt notification even if app is off)
* Email notification between Supervisors when tasks are given and exchanged. 
* Notification when Lab result is sent by Lab officer to supervisor. 
* Notification alert when contact of suspected or confirmed case becomes symptomatic (temperature >=38 celcius, Headaches, etc.)
* Notification alert when there is any form of case disposition from one status to the other. (Suspected case, confirmed case, not a case)
* Trigger alert when lab result is confirmed positive (Text notification, email notification, app notification) 
* Notification alert when a major change has been made to any case file
* Notification alert when a final classification has been assigned to a case.

***Lab Officer***
* Notification alert when a new case has been created within his jurisdiction
* Notification alert when lab specimen and transportation tasks have been done/given
* Notification when Case/surveillance supervisor assigns a task for lab processes


Alerts and Triggers
***Event.rumor officer***
* notification alert when a new rumor event or case information has been created or generated.
* notification alert when a rumor event/case has been dispositioned to a suspected case of said disease
* notification alert when supervisor assigns a task for rumor events.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @StefanSzczesny  Hi Guys, Gerard just finished a live demo presentation on the app in Burkina Faso and some comments below"
1.  Mobile app erratic on mobile hotspot. Saving records, fields disappearing by resetting automatically
2. The Contact officer app did not work, more or less, it did not recieve its task from the supervisor to do contact investigation as well as visits. []In my opinion, i think it is because the current version does not have case synchronized into the build and also a different contact officer might have been assigned a task different from the one who is on the mobile phone. But please do check this in new build.
3. In the future for the pilot, we would prefer to use tablets for the mobile app! Please ensure mobile app is adaptable to tablets. 
4. on the hardware side, no matter which terminal, the keyboard keys must be larger [] In this case, I think we can find android keyboard apps that are bigger and install on all mobile phones for prototype
5.  new cases and tasks should be on top as latest records and not below
6.  Icons / flag for open, invisible inputs etc. (similar to whatsapp) all open tasks or bolden text to show when a new task is available. like whatsapp new incoming messages or gmail new emails.
