### ISSUE TITLE
DateField in symptoms and contact data layouts shouldn't pop up

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#8]
This is caused by the layout auto-focusing the first field and the dateField having a focusListener that shows the pop-up.

Either: Make sure the dateField doesn't show the popup when the focus is set on form enter (see FormTab.addDateField)
Or: Deactivate auto-focus for forms (if possible).

**Comment by MartinWahnschaffeSymeda** [comment]
Tried so far:

in xml:
Im Parent-View folgende Anweisungen setzen:
android:descendantFocusability="beforeDescendants"
android:focusableInTouchMode="true"

in java-Controller (? extends FormTab):
am Ende von onResume():
getView().requestFocus();

**Comment by MateStrysewskeSym** [comment]
Seems to work by adding android:focusable="true" and android:focusableInTouchMode="true" to the layout of the whole form; still needs to be done for all forms, not only the symptoms tab
