### ISSUE TITLE
Prevent creation of new visit after followUpUntil [0.5]

### ISSUE THREAD

**Issue by StefanSzczesny** [hzi-braunschweig/SORMAS-Open#80]
Prevent saving and show a message when the user try to create a visit after te given followUpUntil date from calculated from contact.

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] prevent creation of visits that are more than 10 days before the date of contact or more than 10 days after followUpUntil
- [ ] show all visits of the persons that are within this range

**Comment by MateStrysewskeSym** [comment]
@MartinWahnschaffeSymeda we currently can't implement this validation in the web app when editing visits; possible solutions would be to add a contact field to the visit or to make the visit date and time read-only in the edit form. We need to discuss this.

**Comment by MateStrysewskeSym** [comment]
We decided to not validate the date when editing a visit in the web app. It's still present in the android app but can be removed there, should we implement an option to list all visits (not only of the chosen contact).

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Please make the message for "more than 10 days" more specific.
