### ISSUE TITLE
Update links to cases/events/contacts on task/event person update

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#81]
When updating the associated case/event/contact of a task or the associated person of an event participant, the text on the UI is updated, but still links to the old case/event/contact/person until the user leaves the view or manually refreshes the page. The links should be updated automatically after the respective object has been committed.

**Comment by MartinWahnschaffeSymeda** [comment]
No need to do something about this. It is no longer possible to change the associated object of a task
