### ISSUE TITLE
Country map with state shapes for national user (POS 5) [5]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#82]
Show a country map with shapes of all states. Colorize states by number of cases using the existing dashboard filters. In addition colorize by incidence. The incidence is calculated based on population data from 2013 with estimates on the current population provided by HZI. Needed shapefiles are also provided by HZI. 

This is based on the map component displayed on the dashboard for the supervisor #62 

- [x] use geotools as shapefile reader (LGPL) http://geotools.org/
- [x] import and show shapes of all states. Daniel has provided shapefiles https://www.dropbox.com/s/lvrcx6s1uxjz2kc/Shapefiles.zip?dl=0
- [x] map tiles are not needed - ~~replace vaadin google maps addon with https://vaadin.com/directory#!addon/openlayers-3-wrapper-for-vaadin~~
- [x] national user can switch between shape map and cases map (shapes are default)
- [x] import population data on state level
- [ ] ~~show information (name & numbers) for each region~~ see #350 
- [x] colorize by number of cases using the existing filters
- [x] colorize by incidence (cases per 10.000) using the existing filters
- [x] show legend

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda This will help you determine the incidence rates per disease. Attached is the population data per state 
[Nigeria 2013 Population By States & LGAs Vs.xlsx](https://github.com/hzi-braunschweig/SORMAS-Open/files/913721/Nigeria.2013.Population.By.States.LGAs.Vs.xlsx)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda I have a plan in place to send someone to go a particular LGA possibly Ibadan north to get the coordinates of all the PHC health facilities in that LGA and I will build a quick and dirty app to collect geo coordinates and we can get the coordinates for the LGA we will use for Oyo state. I hope it works out.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Please find attached the updated 2017 population census of Nigeria from the NCDC. Use this instead
[Nigeria 2017 Projected Population.xlsx](https://github.com/hzi-braunschweig/SORMAS-Open/files/1160663/Nigeria.2017.Projected.Population.xlsx)
@gstephan30 @Krisistis

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 What are the thresholds that we should use? E.g. What is the minimum and maximum expected incidence for a given disease. This will define how we colorize the regions.

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Where are the shapefiles you provided from? Are we allowed to use and publish them in SORMAS?

**Comment by dta16** [comment]
Yes you are allowed. Its open source information

**Comment by MartinWahnschaffeSymeda** [comment]
https://vaadin.com/directory#!addon/openlayers-3-wrapper-for-vaadin isn't working very good. It comes with vaadin 8 support, but does not have any documentation and is not usable in an intuitive way.

Probably better to use  open layers javascript https://openlayers.org/en/latest/examples/ in the long term. For now we keep using the google maps vaadin addon and hide the tile images when needed.

**Comment by MartinWahnschaffeSymeda** [comment]
@dta16 Which cases are relevant for the national user's map? Should the system count all reported or only cases that are at least suspected cases?

**Comment by MartinWahnschaffeSymeda** [comment]
Helpful link from daniel http://www.ncdc.gov.ng/reports/81/2017-august-week-34

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] Add date filters to CaseService.getCaseCountPerRegion

**Comment by MartinWahnschaffeSymeda** [comment]
This part of the country map is done. For further implementation see #342 and #350
