### ISSUE TITLE
Add "report" geo coordinates for case, contact, visit, task [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#86]
- [x] add ReportLat, ReportLon to case, contact, event and visit (api, backend, app)
- [x] add ClosedLat, ClosedLon to task (api, backend, app)
- [x] update data dictionary
- [x] fill fields based on phones GPS data
- [x] find a way to update the coordinates without messing up the save system/delaying further usage of the app
- [x] discuss what to do if these entities are created on a non-mobile device (e.g. by a supervisor) or the required permissions are not granted on the phone
- [x] test whether entity creation works
- [x] repair unit tests

[Fake GPS location](https://play.google.com/store/apps/details?id=com.lexa.fakegps&hl=de) should allow us to test this in development. For testing within Android Studio, the emulator provides functionalities to set the phone's geo location.

**Comment by MateStrysewskeSym** [comment]
Problems that we need to take into account:
- App could be closed before a location update is retrieved (in which case the onLocationChanged listener method will never be called)
- GPS could be turned off while creating a new case
- Users could reject the location permission request
- Cases could be created by a supervisor from within the web app

**Comment by MartinWahnschaffeSymeda** [comment]
Solutions:

- [ ] check GPS feature availability on startup of sormas - refuse if no gps available
- [ ] poll GPS every 5 minutes
- [ ] use last gps coordinates when a new case etc. is created and the coordiantes aren't older than 15 minutes

**Comment by MateStrysewskeSym** [comment]
- [ ] request GPS access permission on startup
