### ISSUE TITLE
Remove data from mobile app when no longer needed/assigned/allowed [3]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#87]
Example: The supervisor assigns a case to another district (LGA), because the case was moved to another health facility. Now another surveillance officer is assigned and the previous officer has no longer access.

Question: What about tasks that have previously been assigned to the officer in the example? Does he also no longer have access to them? Or are they still visible but no longer have an active link to the case?

Implementation idea:

- the app requests a complete uuid lists of all accesible cases/contacts/events/tasks/...
- remove all entries from the database that are not in the reply (only if they have already been send to the server)

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda @gstephan30 @stoikkanen: The answer to your question is that the previous tasks assigned to the former officer can still be seen  but will not have an active link to the case. I also agree with your implementation idea. @stoikkanen do you have any contrary opinion?

**Comment by MartinWahnschaffeSymeda** [comment]
implementation of the inactive links is done in #49

**Comment by MartinWahnschaffeSymeda** [comment]
Thoughts on this:
- [ ] Find a way to transfer the ids/uuids in a memory efficient way
- [ ] Do the complete sync once a day
- [ ] Add manual sync option

**Comment by MartinWahnschaffeSymeda** [comment]
We can simply transfer the uuids in a list, because the respone body will be gzipped (OkHttp adds "Accept-Encoding: gzip" by default).

- [ ] Make sure Apache/Payara gzips the data

**Comment by MartinWahnschaffeSymeda** [comment]
It came up that we should better user jersey with jackson instead of moxy (which is payara default). It comes with proper default handlers for things like List<String> and less bugs (see https://stackoverflow.com/questions/19114043/jax-ws-rs-using-jersey-returning-collection-map-etc)

- [ ] use jackson instead of moxy
