### ISSUE TITLE
Custom fields with two-way-binding

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#9]
We need custom fields that implement the PropertyField interface (see SymptomStateField for comparison).

- [x] TextField
- [x] DateField (see FormTab.addDateField)
- [x] SpinnerField (see FormTab.makeSpinnerField; the add*SpinnerField methods probably need a better name afterwards)
- [x] RadioGroupField (e.g. for Contact.contactProximity)
- [x] Label (caption + text; e.g. Case ID in case data form)
- [x] Refactor existing layouts to use these fields.
- [x] Would be great to remove FormTab.getModel.
- [x] Refactoring (-> outsource spinner creation methods)
- [x] Replace age and phone fields with number fields
- [x] Bug: age field edit is not saved
- [x] Bug: Districts and communities are selectable no matter which region/district has been chosen in location dialog

**Comment by MateStrysewskeSym** [comment]
Strings in fieldCaptions.properties sometimes don't match those in the app layout files - which ones should be used?

**Comment by MartinWahnschaffeSymeda** [comment]
The strings in fieldCaptions.properties

Am 30.11.2016 1:49 nachm. schrieb MateStrysewskeSym <notifications@github.com>:

Strings in fieldCaptions.properties sometimes don't match those in the app layout files - which ones should be used?
