### ISSUE TITLE
Case classification for Lassa, HPAI, CSM, Measles, Cholera

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#90]
Define what to do after #61 is implemented.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda We just tested the surveilllance officer dispositioning a case from not yet classified to suspect case and NOte: When mobile phone dispositions from not yet classified, it does not change at the supervisor level. Please check this. Thanks

**Comment by hzi-braunschweig** [comment]
NOte: When mobile phone dispositions from not yet classified, it does not change at the supervisor level. Please check this. Thanks

**Comment by MartinWahnschaffeSymeda** [comment]
Now part of #61
