### ISSUE TITLE
Contact list in app [2]

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#91]
- [x] create mockup
- [x] Acitivity with a list of all contact's the user can access.
- [x] Filter contacts by follow-up status using tabs
- [x] Make sure that users go back to the overall contacts list when pressing the up button
- It is not possible to create new contacts from this activity. This is only possible from within a case.
- see also #93
- case contacts list stays the way it is

**Comment by MateStrysewskeSym** [comment]
It's currently not possible to reliably test the functionality of the filtering because the follow-up status cannot be set to anything except "No follow-up" in the web app.

**Comment by hzi-braunschweig** [comment]
@MartinWahnschaffeSymeda Just a comment on your statement about new contact person creation. You are correct that a new contact is created from a case but speaking from a navigation point of view,  it should be possible for the contact officer to create a new contact person without creating from a case view. What this means is that when he clicks on new contact, he is presented with case list to choose which case he wants to create a contact for.

**Comment by MartinWahnschaffeSymeda** [comment]
We can add this as a new issue for later, but since selectiing the case first and then adding the contact gives the same result we should go with the current solution and prioritize other stuff.
