### ISSUE TITLE
Android bug in cancel function for DateTimeField components -> udpate to android 5.0

### ISSUE THREAD

**Issue by MateStrysewskeSym** [hzi-braunschweig/SORMAS-Open#92]
The "cancel" and "dismiss" functionality for date and time fragments do not work in Android 4.x due to a bug that has been fixed with Android 5.0 (see http://stackoverflow.com/questions/11444238/jelly-bean-datepickerdialog-is-there-a-way-to-cancel/39636443#39636443 and https://code.google.com/p/android/issues/detail?id=34833#c39).

**Comment by MartinWahnschaffeSymeda** [comment]
- [ ] update all devices for table top prototype to android 5.0 (for the LG bello this update is provided by LG and can easily be done)
