### ISSUE TITLE
Update set of task types 

### ISSUE THREAD

**Issue by MartinWahnschaffeSymeda** [hzi-braunschweig/SORMAS-Open#97]
1. Definition (HZI):

- [ ] add lab tasks (?) to the list
- [ ] spilt "who assigns" and "who carries out" columns - for some reason "who assigns" currently has both information.

some questons:

- follow-up duration for hpai?
- follow-up duration for lassa (6-21 days): How are we supposed to implement this? Can we go with a fixed duration? What is the condition for 6 or 21 days?
- what about the tasks that still have questions in the comments?

2. Implementation: 

- [ ] allow TaskType to have a set of TaskContext (e.g. so a task type can be related to a case or event)
- [ ] Update the system with all task types from the data dictionary

**Comment by hzi-braunschweig** [comment]
@stoikkanen some questons:

follow-up duration for hpai?
follow-up duration for lassa (6-21 days): How are we supposed to implement this? Can we go with a fixed duration? What is the condition for 6 or 21 days?
what about the tasks that still have questions in the comments?

**Comment by stoikkanen** [comment]
17 days for hpai, see old process models
lassa 21 days
I will look on the questions asap

**Comment by MartinWahnschaffeSymeda** [comment]
@stoikkanen 
Looks like we forgot to talk about this one in the review. As far as I can tell this still has to be done (labs tasks (?) and split of assigner and assignee - see above). Please also decide on a good name for the "zero report" task and add it to the list.

**Comment by MartinWahnschaffeSymeda** [comment]
@stoikkanen 
Any progress on this one?

**Comment by MartinWahnschaffeSymeda** [comment]
@stoikkanen 
PUSH

**Comment by MartinWahnschaffeSymeda** [comment]
@stoikkanen @dta16 
Please remember we need these urgently!

**Comment by stoikkanen** [comment]
I'm working on this today

**Comment by MartinWahnschaffeSymeda** [comment]
Is this done?

**Comment by MartinWahnschaffeSymeda** [comment]
@MateStrysewskeSym Task type definition is done now and can be implemented.

We should probably talk about this tomorrow:

- [ ] update set of task types
- [x] ignore disease specifics for now
- [ ] add TaskContext "GENERAL" for tasks that are not assigned to a specific entity
- [ ] allow creation of "general" tasks from the overall tasks list
- [ ] allow task types to be used within multiple TaskContextes (e.g. Case and Event)
