### ISSUE TITLE
Notes from Process Model Algorithm

### ISSUE THREAD

**Issue by hzi-braunschweig** [hzi-braunschweig/SORMAS-Open#99]
@gstephan30 @MartinWahnschaffeSymeda @stoikkanen @StefanSzczesny @MateStrysewskeSym 
Process Model Testing

**EBOLA VIRUS DISEASE MODEL**
Informant sub process: Report reminder sent to informant from surveillance mgt at least daily. "Have you had any cases today?" if no case today, a zero report is sent???
1. Once clinician suspects EVD case, informant fills out case investigation form. 
2. Report is sent to the surveillance officer who gets a notification
3. Notification from Surveillance officer is received as feedback about status of case. (not a case, suspected case, confirmed case, probable case with laboratory confirmation)
4. Send Zero reports if no reports for the day. (Note: Zero reporting format???) 

Surveillance Management Team
****Surveillance officer sub process: At the end of each day, check for reports from informant, If no report sent then send reminder to informant. If report from informant is received, then screen informant report; If screened informant report is done and something is wrong then notify informant about outcome else if informant report screening is authentic or rumor event is detected from community then :
1. Coordinate case investigation at health facility/ coordinate incoming rumor event at point of incoming source. case investigation is coordinated for each case report/for each rumor event detected.
2. Confirm investigation as a suspected case detected else state outcome as not a case and revert to active case search or finding.
3. if investigation proves suspected case detected, a notification is sent to Case management team. for further action.
4. If rumor event is received from the community (phone calls, etc) or from the Surveillance supervisor as a task to investigate a rumor event or case then coordinate incoming rumor event and report to State epidemiologist (Surveillance supervisor) if suspected case is detected. A notification is also sent to inform Case management team.

**Case Management Team**
Surveillance Supervisor/Case Supervisor sub process:  For every suspected case detected, a case report is sent to the Surveillance interface. Then:
1. Creates Case Record status based on the suspected case created. Simultaneously Send notification to Contact management team for contact identification and listing based on the suspected case.  
2. Validate Case suspicion (Ebola) Via lab confirmation of results
3. If case is confirmed, then coordinate case handling while observing symptoms
4. if subject is without symptoms then validate Subject discharge (Ebola) based on lab confirmation results.
5. if subject is negative, discharge subject else continue case handling with observation and contact tracking as well as lab results.
6. All contact tracing for the discharged case is cancelled.
7. If subject dies, then initiate coordination of case handling
8. Close Case record.

**Contact Management Team**
Contact supervisor sub process: A notification report is sent to the contact management team immediately a possible case becomes a suspected case. Once report is received then:
1. Identify all contacts for that case; create new contacts for the suspected case. 
2. Coordinate contact investigation
3. If a suspected case is identified from the contact under surveillance then a notification report is sent to Case management team for case handling and investigation
4. if a source case is confirmed not an Ebola case then all contacts are cancelled on that case. 

**Sub Process for Validating Case suspicion (Ebola)**
Case Supervisor begins process once notified of a suspected case from the surveillance team. 
1. Process samples from suspected case. if lab result is inconclusive, process more samples
2. If Sample is negative, then proceed to do another test (2nd test), if sample status is unchanged, change case record to "negative", organize chlorine bath for subject by Case officer (text notification to case officer). Subject new record is sent to Contact supervisor who turns subject into a contact for follow up visits 21 days then released. if no more sample remains to proceed to a 2nd test, then wait minimum of 48 hours to process new sample.
3. if the sample is Positive, then change case record to "Confirmed"

**Sub Process for discharging Case suspicion (Ebola)**
Case Supervisor begins process once notified of a suspected case from the surveillance team. 
1. Process samples from suspected case. if lab result is inconclusive, process more samples
2. If Sample is negative, then proceed to do another test (2nd test), if sample status is unchanged, change case record to "Discharged", organize chlorine bath for subject by Case officer (text notification to case officer). if no more sample remains to proceed to a 2nd test, then wait minimum of 48 hours to process new sample.
3. if the sample is Positive, then reset lab test count to start from the beginning. Wait minimum of 48 hourse then process samples again from subject.

**Sub Process for coordinating Contact investigation (Ebola)**
Contact supervisor gets notification about a suspected case report and coordinates incoming contact identification and tracking. If a new contact is created by Contact officer, a notification is recieved then take corresponding actions:
1. If new contact created, Forward contact to State Epidemiologist (Surveillance supervisor), update contact list and assign contact persons to officers. (Contacts must reside in responsibility area of assigned officer). 
2. If contact is lost to followup then handle lost contact.  Update contact list. (Tasks)
3. If Contact is discharged, prepare discharge of contact (tasks) Update contact list (tasks)
4. If problematic contact, coordinate appropriate contact treatment. update contact list. 
5. if contact officer leaves or new officer joins the team, update contact officer list (staff list).

Contact officer at the start of everyday checks contact list to plan the day. 
1. View contact list for TODAY. Review contact list for the week
2. Check for next contact to visit based on Tasks assigned to officer
3. if contact is on contact group then investigate contact along with source case information. Identify contact by identifying concrete contact with contact data if Contact resides in responsibility area, then add to contact list else Report to contact supervisor for office assignment. updated/new contacts.types of contact for assignment defined.

**Comment by MartinWahnschaffeSymeda** [comment]
@hzi-braunschweig I'd suggest to move this information to the wiki - looks like a good start for it.

**Comment by MartinWahnschaffeSymeda** [comment]
From my understanding this is not an issue but a description of how things work from the user's perspective.
May be used for the SORMAS manual.
